Repository RedHatInsights/catalog-ui, pull requests merged in 2019-07, with the labels that each got.

#219 Added copy portfolio item feature.
  package-lock.json
  package.json
  src/helpers/portfolio/portfolio-helper.js
  src/presentational-components/shared/pf4-select-wrapper.js
  src/redux/actions/portfolio-actions.js
  src/smart-components/common/form-renderer.js
  src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
  src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/test/presentational-components/shared/__snapshots__/pf4-select-wrapper.test.js.snap
  src/test/presentational-components/shared/pf4-select-wrapper.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-description.test.js.snap
Labels: enhancement

#222 Move remove portfolio item action
  config/spandx.config.js
  src/App.scss
  src/smart-components/portfolio/portfolio.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/toolbar/schemas/portfolio-toolbar.schema.js
  src/toolbar/schemas/remove-products-toolbar.schema.js
Labels: enhancement

#223 Fix portfolio-item-card link.
  src/smart-components/portfolio/portfolio-item.js
Labels: bug

#224 Migrate portfolio to function
  package.json
  src/helpers/share/share-helper.js
  src/helpers/shared/redux-mutators.js
  src/smart-components/portfolio/add-products-to-portfolio/index.js
  src/smart-components/portfolio/portfolio-empty-state.js
  src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
  src/smart-components/portfolio/portfolio-items.js
  src/smart-components/portfolio/portfolio.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/toolbar/schemas/portfolio-toolbar.schema.js
Labels: enhancement, technical debt

#221 Disabled pointer events on disabled toolbar links.
  src/App.scss
  src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
  src/toolbar/helpers.js
Labels: bug

#225 Modified order modal to accept different UI schema types.
  package-lock.json
  package.json
  src/presentational-components/shared/pf4-select-wrapper.js
  src/smart-components/order/order-service-form-step-configuration.js
Labels: enhancement

#227 Add pagination portfolios portfolios
  src/helpers/portfolio/portfolio-helper.js
  src/redux/actions/portfolio-actions.js
  src/redux/reducers/portfolio-reducer.js
  src/smart-components/common/async-pagination.js
  src/smart-components/order/order-item.js
  src/smart-components/order/orders.js
  src/smart-components/portfolio/add-portfolio-modal.js
  src/smart-components/portfolio/add-products-to-portfolio/index.js
  src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
  src/smart-components/portfolio/portfolio-items.js
  src/smart-components/portfolio/portfolio.js
  src/smart-components/portfolio/portfolios.js
  src/smart-components/portfolio/remove-portfolio-modal.js
  src/smart-components/portfolio/share-portfolio-modal.js
  src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
  src/test/presentational-components/portfolio/portfolios-filter-toolbar.test.js
  src/test/redux/actions/portfolio-actions.test.js
  src/test/smart-components/portfolio/__snapshots__/portfolios.test.js.snap
  src/test/smart-components/portfolio/add-portfolio-modal.test.js
  src/test/smart-components/portfolio/add-products-to-portfolio/__snapshots__/add-products-pagination.test.js.snap
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-pagination.test.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/test/smart-components/portfolio/portfolios.test.js
  src/test/smart-components/portfolio/remove-portfolio-modal.test.js
  src/test/smart-components/portfolio/share-portfolio-modal.test.js
  src/toolbar/schemas/add-products-toolbar.schema.js
  src/toolbar/schemas/portfolio-toolbar.schema.js
  src/toolbar/schemas/portfolios-toolbar.schema.js
Labels: enhancement

#230 Fix 403 response for portfolios.
  package-lock.json
  package.json
  src/utilities/store.js
Labels: bug

#232 Fixed lingering portfolio data.
  src/redux/action-types.js
  src/redux/actions/portfolio-actions.js
  src/redux/reducers/portfolio-reducer.js
  src/smart-components/portfolio/portfolio.js
  src/test/redux/actions/portfolio-actions.test.js
  src/test/redux/reducers/portfolio-reducer.test.js
Labels: bug

#234 Show description instead of long_description on product card.
  src/presentational-components/shared/service-offering-body.js
Labels: bug

#235 Hide empty attributes in product detail page.
  src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-description.test.js.snap
Labels: bug, technical debt

#229 Add the option to load a platform default icon for products, orders, platform items
  package-lock.json
  package.json
  src/assets/images/amazon-icon.png
  src/assets/images/card-icon-default.png
  src/assets/images/card-icon-default.svg
  src/assets/images/openshift-icon.svg
  src/assets/images/tower-icon.svg
  src/helpers/shared/orders.js
  src/presentational-components/platform/platform-item.js
  src/presentational-components/shared/card-icon.js
  src/smart-components/common/order-modal.js
  src/smart-components/order/order-item.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/portfolio/portfolio-item.js
  src/smart-components/portfolio/portfolio.js
  src/test/presentational-components/platform/__snapshots__/platform-dashboard.test.js.snap
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/presentational-components/platform/platform-item.test.js
  src/test/presentational-components/shared/__snapshots__/loader-placeholders.test.js.snap
  src/test/smart-components/order/__snapshots__/orders.test.js.snap
  src/test/smart-components/platform/__snapshots__/platform.test.js.snap
  src/test/smart-components/platform/__snapshots__/platforms.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/add-portfolio-modal.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolios.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.test.js
  src/test/smart-components/portfolio/portfolio-item.test.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/test/utilities/store.test.js
Labels: enhancement

#237 Fixed portfolio items loading flag.
  src/App.scss
  src/presentational-components/shared/button-with-spinner.js
  src/smart-components/portfolio/portfolio.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
Labels: bug

#236 Change share portfolio action flow.
  package-lock.json
  package.json
  src/presentational-components/shared/pf4-select-wrapper.js
  src/smart-components/portfolio/portfolio-items.js
  src/smart-components/portfolio/portfolios.js
  src/smart-components/portfolio/share-portfolio-modal.js
  src/test/presentational-components/shared/__snapshots__/pf4-select-wrapper.test.js.snap
  src/test/presentational-components/shared/pf4-select-wrapper.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-description.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/item-detail-description.test.js
Labels: technical debt

#238 Fixed share portfolio loader.
  src/forms/portfolio-share-form.schema.js
  src/presentational-components/shared/loader-placeholders.js
  src/smart-components/portfolio/share-portfolio-modal.js
  src/test/smart-components/portfolio/share-portfolio-modal.test.js
Labels: enhancement
