Repository RedHatInsights/catalog-ui, pull requests merged in 2019-11, with the labels that each got.

#286 Sanitize patch requests based on openApi schema
  src/App.js
  src/Routes.js
  src/helpers/portfolio/portfolio-helper.js
  src/helpers/shared/helpers.js
  src/redux/action-types.js
  src/redux/actions/portfolio-actions.js
  src/redux/reducers/open-api-reducer.js
  src/test/__mocks__/open-api-mock.js
  src/test/redux/actions/portfolio-actions.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js
  src/test/utilities/store.test.js
  src/utilities/store.js
Labels: enhancement

#288 Removed console log from test file.
  src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js
Labels: technical debt

#287 Updated share portfolio modal to look more like mocks.
  src/App.scss
  src/forms/form-fields/shage-group-edit.js
  src/forms/form-fields/share-group-select.js
  src/forms/portfolio-share-form.schema.js
  src/presentational-components/shared/loader-placeholders.js
  src/smart-components/common/form-renderer.js
Labels: enhancement

#291 Update pf
  .dependabot/config.yml
  package-lock.json
  package.json
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
Labels: enhancement, technical debt

#292 Removed workflow ref rom portfolio and portfolio item
  src/constants/nullable-attributes.js
  src/forms/edit-portfolio-item-form.schema.js
  src/forms/portfolio-form.schema.js
  src/smart-components/portfolio/add-portfolio-modal.js
  src/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.js
  src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/test/forms/__snapshots__/portfolio-form.schema.test.js.snap
  src/test/forms/portfolio-form.schema.test.js
  src/test/smart-components/portfolio/add-portfolio-modal.test.js
Labels: technical debt

#293 [Stable] PortfolioItem edit hotfix
  src/App.js
  src/Routes.js
  src/forms/edit-portfolio-item-form.schema.js
  src/helpers/portfolio/portfolio-helper.js
  src/helpers/shared/helpers.js
  src/redux/action-types.js
  src/redux/actions/portfolio-actions.js
  src/redux/reducers/open-api-reducer.js
  src/test/__mocks__/open-api-mock.js
  src/test/redux/actions/portfolio-actions.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js
  src/test/utilities/store.test.js
  src/utilities/store.js
Labels: bug

#294 Fixed dropdown styling after PF update
  src/presentational-components/portfolio/porfolio-card.js
  src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/toolbar/schemas/portfolio-toolbar.schema.js
Labels: bug

#297 Add the 'Edit approval workflow' to the portfolio detail kebab menu
  src/presentational-components/portfolio/porfolio-card.js
  src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
  src/smart-components/portfolio/portfolio-items.js
  src/smart-components/portfolio/portfolio.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/toolbar/schemas/portfolio-toolbar.schema.js
Labels: enhancement

#298 Fixed minor prop types errors
  src/presentational-components/portfolio/porfolio-card.js
  src/presentational-components/shared/top-toolbar.js
  src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
  src/smart-components/portfolio/portfolio-items.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/toolbar/schemas/portfolio-toolbar.schema.js
Labels: technical debt

#296 Convert platform templates to use hooks.
  package-lock.json
  src/helpers/platform/platform-helper.js
  src/redux/actions/platform-actions.js
  src/smart-components/platform/platform-templates.js
  src/smart-components/platform/platform.js
  src/smart-components/portfolio/add-products-to-portfolio/index.js
  src/test/redux/actions/platform-actions.test.js
  src/test/smart-components/platform/__snapshots__/platform-templates.test.js.snap
  src/test/smart-components/platform/__snapshots__/platform.test.js.snap
  src/test/smart-components/platform/platform-templates.test.js
  src/test/smart-components/platform/platform.test.js
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
Labels: refactoring

#301 Added the kebab menu with the 'Edit approval for an inventory
  src/smart-components/platform/platform-inventories.js
  src/smart-components/platform/platform-table-helpers.js
  src/test/smart-components/platform/platform-inventories.test.js
  src/utilities/constants.js
Labels: enhancement

#303 Fixed jest-cli security vulnerability
  package-lock.json
Labels: technical debt

#299 Refactor order screens
  package-lock.json
  package.json
  src/App.scss
  src/helpers/order/order-helper.js
  src/helpers/portfolio/portfolio-helper.js
  src/helpers/shared/helpers.js
  src/helpers/shared/orders.js
  src/presentational-components/shared/breadcrubms.js
  src/presentational-components/shared/card-icon.js
  src/presentational-components/shared/loader-placeholders.js
  src/presentational-components/shared/top-toolbar.js
  src/redux/action-types.js
  src/redux/actions/order-actions.js
  src/redux/reducers/order-reducer.js
  src/smart-components/order/cancel-order-modal.js
  src/smart-components/order/create-order-row.js
  src/smart-components/order/order-detail-table.js
  src/smart-components/order/order-detail/approval-request.js
  src/smart-components/order/order-detail/order-detail-information.js
  src/smart-components/order/order-detail/order-detail-menu.js
  src/smart-components/order/order-detail/order-detail-title.js
  src/smart-components/order/order-detail/order-detail.js
  src/smart-components/order/order-detail/order-details.js
  src/smart-components/order/order-detail/order-toolbar-actions.js
  src/smart-components/order/order-item.js
  src/smart-components/order/order-messages-modal.js
  src/smart-components/order/orders-list.js
  src/smart-components/order/orders.js
  src/smart-components/order/orders.scss
  src/smart-components/order/step-label.js
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/presentational-components/shared/__snapshots__/loader-placeholders.test.js.snap
  src/test/presentational-components/shared/__snapshots__/top-toolbar.test.js.snap
  src/test/presentational-components/shared/breadcrumbs.test.js
  src/test/smart-components/order/__snapshots__/order-detail-table.test.js.snap
  src/test/smart-components/order/__snapshots__/orders.test.js.snap
  src/test/smart-components/order/__snapshots__/step-label.test.js.snap
  src/test/smart-components/order/order-detail-table.test.js
  src/test/smart-components/order/orders.test.js
  src/test/smart-components/order/step-label.test.js
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/toolbar/schemas/orders-toolbar.schema.js
Labels: enhancement

#310 Portfolio item routing
  src/helpers/portfolio/portfolio-helper.js
  src/presentational-components/shared/breadcrubms.js
  src/presentational-components/shared/conditional-link.js
  src/presentational-components/shared/service-offering-body.js
  src/redux/action-types.js
  src/redux/actions/portfolio-actions.js
  src/redux/reducers/portfolio-reducer.js
  src/smart-components/common/edit-approval-workflow.js
  src/smart-components/common/order-modal.js
  src/smart-components/order/order-detail/order-detail-menu.js
  src/smart-components/order/order-detail/order-detail.js
  src/smart-components/order/order-service-form-step-configuration.js
  src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
  src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
  src/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.js
  src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/smart-components/portfolio/portfolio-item.js
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/portfolio-item-details.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
  src/utilities/use-query.js
Labels: technical debt

#311 Fixed order detail invalid dates and removed job name.
  src/smart-components/order/order-detail/order-detail-information.js
  src/smart-components/order/order-detail/order-detail.js
  src/smart-components/order/order-detail/order-details.js
Labels: bug

#316 Added ids to portfolio item detail paragraphs.
  src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js
  src/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap
Labels: technical debt

#315 Fixed icon source fallback priority
  src/presentational-components/shared/card-icon.js
Labels: bug

#318 Refactored of order modal.
  src/smart-components/common/order-modal.js
  src/smart-components/order/order-service-form-step-configuration.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/test/smart-components/common/__snapshots__/order-modal.test.js.snap
  src/test/smart-components/common/order-modal.test.js
  src/test/smart-components/order/__snapshots__/order-service-form-step-configuration.test.js.snap
  src/test/smart-components/order/order-mock-form-schema.js
  src/test/smart-components/order/order-service-form-step-configuration.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
  src/test/smart-components/portfolio/portfolio.test.js
Labels: technical debt

#304 Use edit icon endpoint while changing portfolio item icon.
  src/helpers/portfolio/portfolio-helper.js
  src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
Labels: technical debt

#319 Fix for the copy portfolio alert message
  src/redux/actions/portfolio-actions.js
Labels: bug

#320 Orders async filtering
  src/App.scss
  src/helpers/order/order-helper.js
  src/smart-components/common/async-pagination.js
  src/smart-components/order/orders-list.js
  src/test/smart-components/order/orders.test.js
Labels: enhancement

#300 Resolve resource item workflow
  package-lock.json
  package.json
  src/helpers/approval/approval-helper.js
  src/presentational-components/shared/loader-placeholders.js
  src/redux/action-types/approval-action-types.js
  src/redux/actions/approval-actions.js
  src/redux/reducers/approval-reducer.js
  src/smart-components/common/edit-approval-workflow.js
  src/test/smart-components/common/__snapshots__/edit-approval-workflow.test.js.snap
  src/test/smart-components/common/edit-approval-workflow.test.js
  src/test/smart-components/platform/platform-inventories.test.js
Labels: enhancement
