Repository RedHatInsights/catalog-ui, pull requests merged in 2019-01, with the labels that each got.

#34 Force proptypes validation via eslint rule.
  .eslintrc.yml
  package.json
  src/App.js
  src/PresentationalComponents/Platform/PlatformDashboard.js
  src/PresentationalComponents/Platform/PlatformItem.js
  src/PresentationalComponents/Platform/PlatformToolbar.js
  src/PresentationalComponents/Portfolio/PorfolioCard.js
  src/PresentationalComponents/Portfolio/PortfolioOrderToolbar.js
  src/SmartComponents/Common/AddPortfolioModal.js
  src/SmartComponents/Common/EditPortfolioModal.js
  src/SmartComponents/Common/FormRenderer.js
  src/SmartComponents/Common/MainModal.js
  src/SmartComponents/Common/OrderModal.js
  src/SmartComponents/Common/PlatformSelectToolbar.js
  src/SmartComponents/Order/Orders.js
  src/SmartComponents/Platform/PlatformItems.js
  src/SmartComponents/Portfolio/AddProductsToPortfolio.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/SmartComponents/Portfolio/PortfolioItem.js
  src/SmartComponents/Portfolio/Portfolios.js
  src/SmartComponents/ServicePortal/PortalNav.js
Labels: bug

#35 Fix navigation
  src/SmartComponents/ServicePortal/PortalNav.js
  src/SmartComponents/ServicePortal/portalnav.scss
Labels: enhancement

#37 Added routing for portfolio actions.
  src/PresentationalComponents/Portfolio/AddProductsTitleToolbar.js
  src/PresentationalComponents/Portfolio/PortfolioActionToolbar.js
  src/PresentationalComponents/Shared/404Route.js
  src/SmartComponents/Portfolio/AddProductsToPortfolio.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/redux/Actions/PortfolioActions.js
Labels: enhancement

#43 Sort orders by descending create date
  src/SmartComponents/ContentGallery/ContentList.js
Labels: enhancement

#45 Restore portfolio list refresh when adding a portfolio.
  src/SmartComponents/Common/AddPortfolioModal.js
Labels: bug

#39 Portfolio modals
  package.json
  src/PresentationalComponents/Portfolio/PorfolioCard.js
  src/PresentationalComponents/Portfolio/PortfolioActionToolbar.js
  src/Routes.js
  src/SmartComponents/Common/AddPortfolioModal.js
  src/SmartComponents/Common/EditPortfolioModal.js
  src/SmartComponents/Common/MainModal.js
  src/SmartComponents/Common/ModalTypes.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/SmartComponents/Portfolio/Portfolios.js
  src/SmartComponents/Portfolio/add-portfolio-modal.js
  src/SmartComponents/ServicePortal/PortalNav.js
Labels: enhancement

#49 Added pf react tokens to dependencies.
  package.json
Labels: bug

#50 Added error message keys to notifications configuration.
  src/Utilities/store.js
Labels: enhancement

#54 Handle the case when service-portal is considered an unknown app identifier in chrome
  src/App.js
Labels: bug

#55 Add graphql
  package.json
Labels: bug

#48 UI for Remove Portfolio
  src/Helpers/Portfolio/PortfolioHelper.js
  src/PresentationalComponents/Portfolio/PorfolioCard.js
  src/PresentationalComponents/Portfolio/PortfolioActionToolbar.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/SmartComponents/Portfolio/remove-portfolio-modal.js
  src/redux/ActionTypes.js
  src/redux/Actions/PortfolioActions.js
  src/redux/reducers/orderReducer.js
Labels: enhancement

#53 Fix selecting products
  src/Helpers/Platform/PlatformHelper.js
  src/PresentationalComponents/Platform/PlatformItem.js
  src/SmartComponents/Common/PlatformSelectToolbar.js
  src/SmartComponents/Platform/Platform.js
  src/SmartComponents/Portfolio/AddProductsToPortfolio.js
  src/redux/ActionTypes.js
  src/redux/Actions/PlatformActions.js
  src/redux/reducers/platformReducer.js
Labels: bug, enhancement

#47 Api clients package
  .babelrc
  babel.config.js
  config/base.webpack.config.js
  package-lock.json
  package.json
  src/Helpers/Order/OrderHelper.js
  src/Helpers/Platform/PlatformHelper.js
  src/Helpers/Shared/userLogin.js
  src/SmartComponents/ServicePortal/PortalNav.js
  src/Utilities/Constants.js
Labels: enhancement

#59 Added automatic scroll to top on platform/portfolio change.
  src/Helpers/Shared/Helper.js
  src/Helpers/Shared/helpers.js
  src/SmartComponents/Platform/Platform.js
  src/SmartComponents/Platform/Platforms.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/SmartComponents/Portfolio/Portfolios.js
Labels: enhancement

#51 Loading ui placeholders
  package-lock.json
  package.json
  src/PresentationalComponents/Portfolio/PortfolioActionToolbar.js
  src/PresentationalComponents/Shared/LoaderPlaceholders.js
  src/Routes.js
  src/SmartComponents/ContentGallery/ContentGallery.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/SmartComponents/Portfolio/Portfolios.js
  src/SmartComponents/Portfolio/remove-portfolio-modal.js
  src/SmartComponents/ServicePortal/PortalNav.js
  src/Utilities/asyncComponent.js
Labels: enhancement

#58 Connect icon on portfiolio card for removal. Update dialog styling
  package-lock.json
  package.json
  src/Helpers/Portfolio/PortfolioHelper.js
  src/SmartComponents/Portfolio/Portfolios.js
  src/SmartComponents/Portfolio/portfolio.scss
  src/SmartComponents/Portfolio/remove-portfolio-modal.js
  src/Utilities/Constants.js
Labels: enhancement

#52 Platforms and portfolios data loading
  src/SmartComponents/Common/PlatformSelectToolbar.js
  src/SmartComponents/ServicePortal/PortalNav.js
  src/Utilities/store.js
  src/redux/Actions/PlatformActions.js
  src/redux/Actions/PortfolioActions.js
  src/redux/reducers/platformReducer.js
  src/redux/reducers/portfolioReducer.js
Labels: enhancement

#62 Revert changes for topology service path
  src/Utilities/Constants.js
Labels: bug

#60 Added filtering of portfolios
  src/PresentationalComponents/Portfolio/PortfoliosFilterToolbar.js
  src/PresentationalComponents/Shared/FilterToolbarItem.js
  src/SmartComponents/ContentGallery/ContentGallery.js
  src/SmartComponents/Portfolio/Portfolios.js
Labels: enhancement

#63 Added filtering for products.
  src/PresentationalComponents/Shared/FilterToolbarItem.js
  src/SmartComponents/Common/PlatformSelectToolbar.js
  src/SmartComponents/Portfolio/AddProductsToPortfolio.js
Labels: enhancement

#64 Fixed wrong styling on portfolio toolbar dropdown.
  package-lock.json
  package.json
  src/PresentationalComponents/Portfolio/PortfolioActionToolbar.js
  src/PresentationalComponents/Portfolio/PortfoliosFilterToolbar.js
Labels: bug

#66 Add link to portfolio on card click.
  src/PresentationalComponents/Portfolio/PorfolioCard.js
  src/SmartComponents/Portfolio/Portfolios.js
Labels: enhancement

#15 Add component for removing portfolio items
  src/Helpers/Portfolio/PortfolioHelper.js
  src/PresentationalComponents/Portfolio/PortfolioActionToolbar.js
  src/SmartComponents/Common/CardCheckbox.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/SmartComponents/Portfolio/PortfolioItem.js
  src/SmartComponents/Portfolio/RemovePortfolioItems.js
  src/SmartComponents/Portfolio/removeportfolioitems.scss
  src/SmartComponents/ServicePortal/PortalNav.js
  src/SmartComponents/ServicePortal/portalnav.scss
  src/Utilities/store.js
  src/redux/Actions/UiActions.js
  src/redux/reducers/UiReducer.js
Labels: enhancement

#68 Added correct spacing for action toolbars.
  src/App.scss
  src/PresentationalComponents/Portfolio/PortfolioActionToolbar.js
  src/SmartComponents/Platform/Platform.js
  src/SmartComponents/Platform/Platforms.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/SmartComponents/Portfolio/Portfolios.js
Labels: enhancement

#72 Added proper parameters to show modal actions.
  src/SmartComponents/Portfolio/PortfolioItem.js
Labels: bug

#74 Order data driven form
  package-lock.json
  package.json
  src/SmartComponents/Order/OrderServiceFormStepConfiguration.js
Labels: enhancement

#76 Fixed header generating form orders table.
  src/SmartComponents/ContentGallery/ContentList.js
Labels: bug

#77 Added sendSubmitOrder to mapDispatchToProps and send correct data.
  src/SmartComponents/Order/OrderServiceFormStepConfiguration.js
Labels: bug

#78 Change Add Products button type and set to disable when no products are selected
  src/PresentationalComponents/Portfolio/AddProductsTitleToolbar.js
  src/SmartComponents/Portfolio/AddProductsToPortfolio.js
Labels: bug

#75 Order dialog update
  src/PresentationalComponents/Portfolio/PortfolioActionToolbar.js
  src/SmartComponents/Common/MainModal.js
  src/SmartComponents/Common/OrderModal.js
  src/SmartComponents/Common/mainmodal.scss
  src/SmartComponents/Common/orderservice.scss
  src/SmartComponents/Order/OrderServiceFormStepConfiguration.js
  src/SmartComponents/Order/OrderServiceFormStepInformation.js
  src/SmartComponents/Order/orderservice.scss
Labels: enhancement

#71 Tests for redux portfolio actions
  config/setupTests.js
  package-lock.json
  package.json
  src/Helpers/Portfolio/PortfolioHelper.js
  src/redux/Actions/PortfolioActions.js
  src/test/.eslintrc
  src/test/redux/actions/portfolio-actions.test.js
Labels: test
