Repository RedHatInsights/catalog-ui, pull requests merged in 2019-08, with the labels that each got.

#239 Updated axios to fix security vulnerabilities.
  package-lock.json
  package.json
Labels: technical debt

#240 Added open and closed orders tabs
  src/presentational-components/shared/loader-placeholders.js
  src/smart-components/order/orders.js
  src/test/smart-components/order/__snapshots__/orders.test.js.snap
  src/test/smart-components/order/orders.test.js
  src/toolbar/schemas/orders-toolbar.schema.js
Labels: enhancement

#242 Replaced ordered at with created at date for orders.
  src/smart-components/order/order-item.js
Labels: bug

#243 Fix portfolio card link.
  src/presentational-components/portfolio/porfolio-card.js
  src/presentational-components/portfolio/portfolio-card-header.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/presentational-components/portfolio/portfolio-card-header.test.js
Labels: bug

#244 Fixed message and Add Products link on the Empty Portfolio page
  src/smart-components/portfolio/portfolio-items.js
Labels: bug

#245 Added select with asynchronous filtering.
  package-lock.json
  package.json
  src/forms/portfolio-form.schema.js
  src/helpers/approval/approval-helper.js
  src/presentational-components/shared/pf4-select-wrapper.js
  src/smart-components/portfolio/add-portfolio-modal.js
  src/test/forms/__snapshots__/portfolio-form.schema.test.js.snap
  src/test/smart-components/portfolio/add-portfolio-modal.test.js
Labels: enhancement

#247 Added canceled order to closed orders
  src/redux/actions/order-actions.js
  src/smart-components/order/create-order-row.js
  src/test/redux/actions/order-actions.test.js
Labels: enhancement

#248 Removed platformId undefined override in card icon component.
  src/presentational-components/shared/card-icon.js
Labels: bug

#246 Filter sources by application type
  src/helpers/platform/platform-helper.js
  src/helpers/shared/user-login.js
  src/redux/actions/platform-actions.js
  src/test/redux/actions/platform-actions.test.js
  src/test/smart-components/platform/platforms.test.js
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/utilities/store.js
Labels: enhancement

#250 Fetch platforms before showing orders.
  src/presentational-components/shared/card-icon.js
  src/smart-components/order/orders.js
Labels: bug

#251 Fixed platforms empty state link to sources.
  src/smart-components/platform/platforms.js
Labels: bug

#253 Update react 16.9
  package-lock.json
  package.json
  src/redux/actions/portfolio-actions.js
  src/redux/reducers/portfolio-reducer.js
  src/smart-components/portfolio/remove-portfolio-modal.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
  src/test/presentational-components/portfolio/portfolio-card-header.test.js
  src/test/presentational-components/portfolio/portfolios-filter-toolbar.test.js
  src/test/redux/reducers/portfolio-reducer.test.js
  src/test/smart-components/order/order-mock-form-schema.js
  src/test/smart-components/order/order-service-form-step-configuration.test.js
  src/test/smart-components/order/orders.test.js
  src/test/smart-components/portfolio/__snapshots__/add-portfolio-modal.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolios.test.js.snap
  src/test/smart-components/portfolio/add-portfolio-modal.test.js
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/test/smart-components/portfolio/portfolios.test.js
  src/test/smart-components/portfolio/remove-portfolio-modal.test.js
  src/test/smart-components/portfolio/share-portfolio-modal.test.js
Labels: technical debt

#254 Fixed wrong redirect when closing order progress messages.
  src/smart-components/order/order-detail-table.js
  src/smart-components/order/order-messages-modal.js
  src/smart-components/order/orders-list.js
  src/smart-components/order/orders.js
Labels: bug
