Repository RedHatInsights/catalog-ui, pull requests merged in 2019-04, with the labels that each got.

#142 Added dropdown and last update date to portfolio card.
  src/App.scss
  src/presentational-components/portfolio/porfolio-card.js
  src/presentational-components/portfolio/portfolio-card-header.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/presentational-components/portfolio/portfolio-card.test.js
  src/utilities/constants.js
Labels: enhancement

#143 Fixed wrong query param for service offerings.
  src/helpers/platform/platform-helper.js
  src/test/redux/actions/platform-actions.test.js
  src/test/smart-components/platform/platform.test.js
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-pagination.test.js
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
Labels: bug

#133 Add portfolios sharing unsharing
  config/spandx.config.js
  package-lock.json
  package.json
  src/forms/portfolio-share-form.schema.js
  src/helpers/rbac/rbac-helper.js
  src/helpers/share/share-helper.js
  src/helpers/shared/user-login.js
  src/presentational-components/portfolio/porfolio-card.js
  src/presentational-components/portfolio/portfolio-filter-toolbar.js
  src/presentational-components/shared/loader-placeholders.js
  src/redux/action-types.js
  src/redux/actions/rbac-actions.js
  src/redux/actions/share-actions.js
  src/redux/reducers/rbac-reducer.js
  src/redux/reducers/share-reducer.js
  src/smart-components/portfolio/portfolio.js
  src/smart-components/portfolio/portfolios.js
  src/smart-components/portfolio/share-portfolio-modal.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-filter-toolbar.test.js.snap
  src/test/redux/actions/rbac-actions.test.js
  src/test/redux/reducers/rbac-reducer.test.js
  src/test/redux/reducers/share-reducer.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.test.js
  src/utilities/constants.js
  src/utilities/store.js
Labels: enhancement

#146 Updated portfolio card to match mocks.
  src/helpers/shared/helpers.js
  src/presentational-components/portfolio/porfolio-card.js
  src/presentational-components/portfolio/portfolio-card-header.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/utilities/constants.js
Labels: enhancement

#145 Portfolio items icons
  package-lock.json
  package.json
  src/App.scss
  src/presentational-components/shared/card-icon.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/portfolio/portfolio-item.js
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
Labels: enhancement

#151 Fix card line clamping in Firefox.
  package-lock.json
  package.json
  src/presentational-components/shared/card-common.js
  src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
  src/test/presentational-components/shared/__snapshots__/card-common.test.js.snap
  src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap
Labels: bug

#153 Empty states for platforms portfolios and portfolio screens
  src/presentational-components/shared/content-gallery-empty-state.js
  src/smart-components/content-gallery/content-gallery.js
  src/smart-components/platform/platforms.js
  src/smart-components/portfolio/portfolio.js
  src/smart-components/portfolio/portfolios.js
  src/test/smart-components/content-gallery/__snapshots__/content-gallery.test.js.snap
  src/test/smart-components/portfolio/portfolio.test.js
Labels: enhancement

#154 Remove link from Settings text in empty state.
  src/smart-components/platform/platforms.js
Labels: bug

#155 Fixed build bundle size.
  config/base.webpack.config.js
  package-lock.json
  package.json
  src/presentational-components/shared/breadcrubms.js
  src/smart-components/order/create-order-row.js
  src/smart-components/portfolio/add-products-to-portfolio/index.js
  src/smart-components/portfolio/remove-portfolio-modal.js
  src/test/presentational-components/platform/__snapshots__/platform-dashboard.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-filter-toolbar.test.js.snap
Labels: bug

#156 Fixed webpack SCSS tree shaking.
  config/base.webpack.config.js
  package.json
Labels: bug

#157 Added missing env variable for prod build.
  package.json
Labels: bug

#159 Added empty states for add products to portfolio screen.
  src/smart-components/portfolio/add-products-to-portfolio/add-products-gallery.js
  src/smart-components/portfolio/add-products-to-portfolio/index.js
  src/test/smart-components/portfolio/add-products-to-portfolio/__snapshots__/add-products-gallery.test.js.snap
Labels: enhancement

#158 Fixed styling for tollbar filter inputs.
  src/App.scss
  src/constants/select-styles-override.js
  src/presentational-components/portfolio/portfolio-order-toolbar.js
  src/presentational-components/shared/filter-toolbar-item.js
  src/test/presentational-components/shared/__snapshots__/filter-toolbar-item.test.js.snap
  src/test/presentational-components/shared/filter-toolbar-item.test.js
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
Labels: enhancement

#161 Moved portfolio toolbar buttons.
  src/App.scss
  src/presentational-components/portfolio/portfolio-filter-toolbar.js
  src/smart-components/portfolio/portfolio.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-filter-toolbar.test.js.snap
Labels: enhancement

#164 Update redux state correctly after updating portfolio.
  src/helpers/portfolio/portfolio-helper.js
  src/redux/reducers/portfolio-reducer.js
Labels: bug

#163 Added redux action creator for remove items from portfolio.
  src/redux/action-types.js
  src/redux/actions/portfolio-actions.js
  src/smart-components/portfolio/portfolio.js
  src/test/smart-components/portfolio/portfolio.test.js
Labels: bug

#168 Fix tests console errors.
  src/presentational-components/shared/card-common.js
  src/presentational-components/shared/pf4-select-wrapper.js
  src/smart-components/common/order-modal.js
  src/smart-components/order/orders.js
  src/smart-components/platform/platform.js
  src/smart-components/portfolio/add-portfolio-modal.js
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/presentational-components/platform/platform-item.test.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-filter-toolbar.test.js.snap
  src/test/presentational-components/portfolio/portfolio-card.test.js
  src/test/presentational-components/portfolio/portfolio-filter-toolbar.test.js
  src/test/smart-components/order/orders.test.js
  src/test/smart-components/platform/__snapshots__/platform.test.js.snap
  src/test/smart-components/platform/platform.test.js
  src/test/smart-components/portfolio/__snapshots__/add-portfolio-modal.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolios.test.js.snap
  src/test/smart-components/portfolio/add-portfolio-modal.test.js
  src/test/smart-components/portfolio/add-products-to-portfolio/__snapshots__/add-products-to-portfolio.test.js.snap
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-description.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/item-detail-description.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/test/smart-components/portfolio/portfolios.test.js
  src/test/smart-components/portfolio/remove-portfolio-modal.test.js
Labels: technical debt

#160 Add NODE_OPTIONS to avoid fatal error during build.
  .travis.yml
Labels: bug

#172 Added correct icons to order steps.
  src/smart-components/order/create-order-row.js
Labels: bug

#169 Added axios error interceptor.
  src/helpers/shared/user-login.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/utilities/store.js
Labels: enhancement

#178 Fixed order modal header icon and text sizing.
  src/smart-components/common/order-modal.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
Labels: bug

#180 Added time and UTC tool tip for order relative dates.
  src/helpers/shared/helpers.js
  src/smart-components/order/create-order-row.js
  src/smart-components/order/order-detail-table.js
  src/smart-components/order/order-item.js
  src/test/smart-components/order/__snapshots__/order-detail-table.test.js.snap
Labels: enhancement

#184 Added global redux rejected loading handler.
  src/redux/action-types.js
  src/redux/reducers/approval-reducer.js
  src/redux/reducers/order-reducer.js
  src/redux/reducers/platform-reducer.js
  src/redux/reducers/portfolio-reducer.js
  src/redux/reducers/rbac-reducer.js
  src/redux/reducers/share-reducer.js
  src/utilities/loading-state-middleware.js
  src/utilities/store.js
Labels: enhancement
