Repository RedHatInsights/catalog-ui, pull requests merged in 2019-12, with the labels that each got.

#332 Fixed left spacing for toolbars
  src/presentational-components/shared/top-toolbar.js
  src/test/presentational-components/shared/__snapshots__/top-toolbar.test.js.snap
  src/toolbar/toolbar-mapper.js
Labels: bug

#330 Update react core version
  package-lock.json
  package.json
  src/test/presentational-components/shared/__snapshots__/filter-toolbar-item.test.js.snap
Labels: unmergeable

#336 Update ddf to fix select portaling.
  package-lock.json
  package.json
  src/presentational-components/shared/pf4-select-wrapper.js
Labels: enhancement

#338 Added basic survey editing.
  package-lock.json
  package.json
  src/helpers/shared/user-login.js
  src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/smart-components/survey-editing/survey-editor.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
Labels: enhancement

#342 Fixed up toolbar spacing
  src/presentational-components/shared/breadcrubms.js
  src/presentational-components/shared/top-toolbar.js
  src/smart-components/common/async-pagination.js
  src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
  src/test/presentational-components/shared/__snapshots__/top-toolbar.test.js.snap
  src/test/smart-components/order/__snapshots__/orders.test.js.snap
  src/toolbar/schemas/orders-toolbar.schema.js
  src/toolbar/schemas/portfolios-toolbar.schema.js
  src/toolbar/schemas/products-toolbar.schema.js
  src/toolbar/toolbar-mapper.js
Labels: enhancement

#343 Empty states
  src/app-context.js
  src/entry-dev.js
  src/entry.js
  src/presentational-components/shared/content-gallery-empty-state.js
  src/smart-components/order/orders-list.js
  src/smart-components/platform/platform-templates.js
  src/smart-components/portfolio/portfolio-empty-state.js
  src/smart-components/portfolio/portfolio-items.js
  src/smart-components/products/products.js
Labels: enhancement

#345 Disabled non-existing products links.
  src/smart-components/portfolio/portfolio-item.js
  src/smart-components/portfolio/portfolio.js
  src/smart-components/products/products.js
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
Labels: bug

#341 Added more controls to suver editor overlay
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/smart-components/survey-editing/survey-editor.js
Labels: enhancement

#346 Add manage product link
  src/smart-components/order/order-detail/order-detail-menu.js
  src/smart-components/order/order-detail/order-detail.js
  src/smart-components/order/order-detail/order-lifecycle.js
Labels: bug

#347 Update survey editor to allow validation editing.
  package-lock.json
  package.json
Labels: enhancement

#349 Updated permission verbs to the new version
  src/smart-components/portfolio/share-portfolio-modal.js
  src/test/smart-components/portfolio/share-portfolio-modal.test.js
  src/utilities/constants.js
Labels: enhancement, pending
