Repository RedHatInsights/catalog-ui, pull requests merged in 2019-03, with the labels that each got.

#109 Remove secondary nav
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/PresentationalComponents/Platform/PlatformCard.js
  src/PresentationalComponents/Platform/PlatformItem.js
  src/PresentationalComponents/Portfolio/PorfolioCard.js
  src/PresentationalComponents/Portfolio/PortfoliosFilterToolbar.js
  src/Routes.js
  src/SmartComponents/ContentGallery/ContentGallery.js
  src/SmartComponents/Platform/Platforms.js
  src/SmartComponents/Portfolio/AddProductsToPortfolio.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/SmartComponents/Portfolio/PortfolioItem.js
  src/SmartComponents/Portfolio/Portfolios.js
  src/SmartComponents/ServicePortal/PortalNav.js
  src/SmartComponents/ServicePortal/portalnav.scss
  src/redux/Actions/PlatformActions.js
  src/redux/Actions/PortfolioActions.js
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/presentional-components/platform/__snapshots__/platform-card.test.js.snap
  src/test/redux/actions/__snapshots__/platform-actions.test.js.snap
  src/test/redux/actions/platform-actions.test.js
  src/test/redux/actions/portfolio-actions.test.js
  src/test/smart-components/content-gallery/__snapshots__/content-gallery.test.js.snap
  src/test/smart-components/platform/platforms.test.js
Labels: enhancement

#111 Use gallery component for portfolio/platforms card layouts.
  src/PresentationalComponents/Platform/PlatformCard.js
  src/PresentationalComponents/Portfolio/PorfolioCard.js
  src/SmartComponents/ContentGallery/ContentGallery.js
  src/SmartComponents/Portfolio/PortfolioItem.js
  src/test/presentional-components/platform/__snapshots__/platform-card.test.js.snap
  src/test/smart-components/content-gallery/__snapshots__/content-gallery.test.js.snap
Labels: enhancement

#110 Update toolbars
  .babelrc
  config/base.webpack.plugins.js
  package-lock.json
  package.json
  src/App.scss
  src/PresentationalComponents/Platform/PlatformDashboard.js
  src/PresentationalComponents/Platform/PlatformToolbar.js
  src/PresentationalComponents/Portfolio/PortfolioActionToolbar.js
  src/PresentationalComponents/Portfolio/PortfolioFilterToolbar.js
  src/PresentationalComponents/Portfolio/PortfolioOrderToolbar.js
  src/PresentationalComponents/Shared/LoaderPlaceholders.js
  src/PresentationalComponents/Shared/OrderToolbarItem.js
  src/PresentationalComponents/Shared/breadcrubms.js
  src/PresentationalComponents/Shared/top-toolbar.js
  src/PresentationalComponents/Shared/top-toolbar.scss
  src/SmartComponents/Order/orders-toolbar.js
  src/SmartComponents/Platform/Platform.js
  src/SmartComponents/Platform/Platforms.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/SmartComponents/Portfolio/Portfolios.js
  src/SmartComponents/Portfolio/RemovePortfolioItems.js
  src/test/.eslintrc
  src/test/presentational-components/platform/__snapshots__/platform-dashboard.test.js.snap
  src/test/presentational-components/platform/__snapshots__/platform-toolbar.test.js.snap
  src/test/presentational-components/platform/platform-toolbar.test.js
  src/test/presentional-components/shared/__snapshots__/breadcrumbs.test.js.snap
  src/test/presentional-components/shared/__snapshots__/loader-placeholders.test.js.snap
  src/test/presentional-components/shared/__snapshots__/order-toolbar-item.test.js.snap
  src/test/presentional-components/shared/__snapshots__/top-toolbar.test.js.snap
  src/test/presentional-components/shared/breadcrumbs.test.js
  src/test/presentional-components/shared/loader-placeholders.test.js
  src/test/presentional-components/shared/order-toolbar-item.test.js
  src/test/presentional-components/shared/top-toolbar.test.js
  src/test/redux/redux-helpers.js
  src/test/smart-components/platform/platform.test.js
  src/test/smart-components/platform/platforms.test.js
Labels: bug, enhancement

#112 Platform pagination
  package-lock.json
  package.json
  src/Helpers/Platform/PlatformHelper.js
  src/Helpers/Shared/pagination.js
  src/PresentationalComponents/Platform/PlatformToolbar.js
  src/PresentationalComponents/Shared/LoaderPlaceholders.js
  src/SmartComponents/Platform/Platform.js
  src/SmartComponents/Portfolio/AddProductsToPortfolio.js
  src/redux/Actions/PlatformActions.js
  src/test/presentational-components/platform/__snapshots__/platform-toolbar.test.js.snap
  src/test/presentional-components/shared/__snapshots__/loader-placeholders.test.js.snap
  src/test/redux/actions/platform-actions.test.js
  src/test/smart-components/content-gallery/__snapshots__/content-gallery.test.js.snap
  src/test/smart-components/platform/__snapshots__/platform.test.js.snap
  src/test/smart-components/platform/platform.test.js
Labels: enhancement

#107 Product detail page.
  config/dev.webpack.config.js
  src/Helpers/Portfolio/PortfolioHelper.js
  src/PresentationalComponents/Shared/LoaderPlaceholders.js
  src/PresentationalComponents/Shared/breadcrubms.js
  src/SmartComponents/Common/FormRenderer.js
  src/SmartComponents/Common/OrderModal.js
  src/SmartComponents/Order/OrderServiceFormStepConfiguration.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/SmartComponents/Portfolio/PortfolioItem.js
  src/SmartComponents/Portfolio/portfolio-item-detail.js
  src/redux/Actions/PortfolioActions.js
  src/test/redux/actions/portfolio-actions.test.js
Labels: enhancement

#115 Add products pagination
  src/PresentationalComponents/Portfolio/PortfolioOrderToolbar.js
  src/SmartComponents/Portfolio/AddProductsToPortfolio.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/SmartComponents/Portfolio/add-products-to-portfolio/add-products-gallery.js
  src/SmartComponents/Portfolio/add-products-to-portfolio/add-products-pagination.js
  src/SmartComponents/Portfolio/add-products-to-portfolio/index.js
  src/test/smart-components/portfolio/add-products-to-portfolio/__snapshots__/add-products-gallery.test.js.snap
  src/test/smart-components/portfolio/add-products-to-portfolio/__snapshots__/add-products-pagination.test.js.snap
  src/test/smart-components/portfolio/add-products-to-portfolio/__snapshots__/add-products-to-portfolio.test.js.snap
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-gallery.test.js
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-pagination.test.js
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
Labels: enhancement

#116 Approval workflow
  package-lock.json
  package.json
  src/Helpers/approval/approval-helper.js
  src/SmartComponents/Portfolio/add-portfolio-modal.js
  src/Utilities/Constants.js
  src/Utilities/store.js
  src/forms/portfolio-form.schema.js
  src/redux/ActionTypes/action-types-helper.js
  src/redux/ActionTypes/approval-action-types.js
  src/redux/Actions/PortfolioActions.js
  src/redux/Actions/approval-actions.js
  src/redux/reducers/approval-reducer.js
  src/test/forms/__snapshots__/portfolio-form.schema.test.js.snap
  src/test/forms/portfolio-form.schema.test.js
  src/test/redux/actions/approval-actions.test.js
  src/test/redux/reducers/approval-reducer.test.js
  src/test/smart-components/portfolio/__snapshots__/add-portfolio-modal.test.js.snap
  src/test/smart-components/portfolio/add-portfolio-modal.test.js
Labels: enhancement, test

#118 Tests audit
  src/PresentationalComponents/Portal/Portal.js
  src/PresentationalComponents/Portal/Portal.scss
  src/SmartComponents/Catalog/Catalog.js
  src/SmartComponents/Catalog/catalog.scss
  src/SmartComponents/Order/orders-toolbar.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/SmartComponents/Portfolio/Portfolios.js
  src/redux/ActionTypes/UiActionTypes.js
  src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
  src/test/presentational-components/platform/platform-card.test.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-filter-toolbar.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
  src/test/presentational-components/portfolio/portfolio-card-header.test.js
  src/test/presentational-components/portfolio/portfolio-card.test.js
  src/test/presentational-components/portfolio/portfolio-filter-toolbar.test.js
  src/test/presentational-components/portfolio/portfolios-filter-toolbar.test.js
  src/test/presentational-components/shared/404Route.test.js
  src/test/presentational-components/shared/__snapshots__/404Route.test.js.snap
  src/test/presentational-components/shared/__snapshots__/breadcrumbs.test.js.snap
  src/test/presentational-components/shared/__snapshots__/card-checkbox.test.js.snap
  src/test/presentational-components/shared/__snapshots__/card-common.test.js.snap
  src/test/presentational-components/shared/__snapshots__/filter-toolbar-item.test.js.snap
  src/test/presentational-components/shared/__snapshots__/image-with-default.test.js.snap
  src/test/presentational-components/shared/__snapshots__/loader-placeholders.test.js.snap
  src/test/presentational-components/shared/__snapshots__/pf4-select-wrapper.test.js.snap
  src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap
  src/test/presentational-components/shared/__snapshots__/top-toolbar.test.js.snap
  src/test/presentational-components/shared/breadcrumbs.test.js
  src/test/presentational-components/shared/card-checkbox.test.js
  src/test/presentational-components/shared/card-common.test.js
  src/test/presentational-components/shared/filter-toolbar-item.test.js
  src/test/presentational-components/shared/image-with-default.test.js
  src/test/presentational-components/shared/loader-placeholders.test.js
  src/test/presentational-components/shared/pf4-select-wrapper.test.js
  src/test/presentational-components/shared/service-offering-body.test.js
  src/test/presentational-components/shared/top-toolbar.test.js
  src/test/smart-components/common/__snapshots__/order-modal.test.js.snap
  src/test/smart-components/common/order-modal.test.js
  src/test/smart-components/order/__snapshots__/orders-toolbar.test.js.snap
  src/test/smart-components/order/__snapshots__/orders.test.js.snap
  src/test/smart-components/order/orders-toolbar.test.js
  src/test/smart-components/order/orders.test.js
  src/test/smart-components/platform/platform.test.js
  src/test/smart-components/portfolio/__snapshots__/portfolio-item-details.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolio.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolios.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/remove-portfolio-items.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/remove-portfolio-modal.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-details.test.js
  src/test/smart-components/portfolio/portfolio-item.test.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/test/smart-components/portfolio/portfolios.test.js
  src/test/smart-components/portfolio/remove-portfolio-items.test.js
  src/test/smart-components/portfolio/remove-portfolio-modal.test.js
Labels: technical debt, test

#120 Added update portfolio item
  src/Helpers/Portfolio/PortfolioHelper.js
  src/Helpers/Shared/helpers.js
  src/PresentationalComponents/Shared/breadcrubms.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/SmartComponents/Portfolio/PortfolioItem.js
  src/SmartComponents/Portfolio/portfolio-item-detail.js
  src/SmartComponents/Portfolio/portfolio-item-detail/detail-toolbar-actions.js
  src/SmartComponents/Portfolio/portfolio-item-detail/edit-toolbar-actions.js
  src/SmartComponents/Portfolio/portfolio-item-detail/item-detail-description.js
  src/SmartComponents/Portfolio/portfolio-item-detail/item-detail-info-bar.js
  src/SmartComponents/Portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/SmartComponents/Portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/redux/ActionTypes.js
  src/redux/Actions/PortfolioActions.js
  src/redux/reducers/portfolioReducer.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/edit-toolbar-actions.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-description.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/portfolio-item-detail-toolbar.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/portfolio-item-details.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/edit-toolbar-actions.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/item-detail-description.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
  src/test/smart-components/portfolio/portfolio-item-details.test.js
Labels: enhancement

#123 Added service offerings icons to UI.
  src/PresentationalComponents/Platform/PlatformItem.js
  src/PresentationalComponents/Shared/LoaderPlaceholders.js
  src/PresentationalComponents/Shared/card-icon.js
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
Labels: enhancement

#121 Removed initial step from portfolio item ordering dialog.
  src/SmartComponents/Common/OrderModal.js
  src/SmartComponents/Order/OrderServiceFormConstants.js
  src/SmartComponents/Order/OrderServiceFormStepConfiguration.js
  src/SmartComponents/Order/OrderServiceFormStepInformation.js
  src/SmartComponents/Order/orderservice.scss
  src/Utilities/jschema.scss
  src/test/smart-components/common/order-modal.test.js
  src/test/smart-components/order/__snapshots__/order-service-form-step-configuration.test.js.snap
  src/test/smart-components/order/order-mock-form-schema.js
  src/test/smart-components/order/order-service-form-step-configuration.test.js
Labels: bug

#124 UI styling clean up
  package-lock.json
  package.json
  src/App.scss
  src/PresentationalComponents/Platform/PlatformCard.js
  src/PresentationalComponents/Platform/platform.scss
  src/PresentationalComponents/Platform/platformcard.scss
  src/PresentationalComponents/Portfolio/PortfolioFilterToolbar.js
  src/PresentationalComponents/Portfolio/PortfolioOrderToolbar.js
  src/PresentationalComponents/Shared/toolbarschema.scss
  src/SmartComponents/Common/orderservice.scss
  src/SmartComponents/ContentGallery/ContentGallery.js
  src/SmartComponents/ContentGallery/content-gallery.scss
  src/SmartComponents/Platform/Platform.js
  src/SmartComponents/Platform/Platforms.js
  src/SmartComponents/Platform/platform.scss
  src/SmartComponents/Portfolio/Portfolio.js
  src/SmartComponents/Portfolio/Portfolios.js
  src/SmartComponents/Portfolio/RemovePortfolioItems.js
  src/SmartComponents/Portfolio/portfolio.scss
  src/SmartComponents/Portfolio/remove-portfolio-modal.js
  src/SmartComponents/Portfolio/removeportfolioitems.scss
  src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-filter-toolbar.test.js.snap
  src/test/smart-components/content-gallery/__snapshots__/content-gallery.test.js.snap
  src/test/smart-components/platform/__snapshots__/platforms.test.js.snap
Labels: bug

#125 Fixed missing URL for closing the order modal after submit.
  src/SmartComponents/Common/OrderModal.js
  src/SmartComponents/Order/OrderServiceFormStepConfiguration.js
  src/test/smart-components/order/order-service-form-step-configuration.test.js
Labels: bug

#129 Add missing notification after ordering success.
  src/redux/Actions/OrderActions.js
  src/test/redux/actions/order-actions.test.js
Labels: bug

#131 master is beta for deployment purposes
  config/webpack.common.js
Labels: bug

#132 Added scroll polyfill to support older browsers.
  package-lock.json
  package.json
  src/App.js
Labels: bug

#138 Fixed ui not rendering.
  config/webpack.common.js
  package-lock.json
  package.json
  src/entry-dev.js
  src/entry.js
  src/helpers/order/order-helper.js
  src/helpers/shared/user-login.js
  src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-filter-toolbar.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
  src/test/redux/actions/portfolio-actions.test.js
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/remove-portfolio-items.test.js.snap
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/edit-toolbar-actions.test.js.snap
  src/utilities/constants.js
Labels: bug

#139 Use axios generated client for catalog API.
  package-lock.json
  package.json
  src/helpers/order/order-helper.js
  src/helpers/portfolio/portfolio-helper.js
  src/helpers/shared/user-login.js
  src/test/helpers/shared/user-login.test.js
  src/test/redux/actions/portfolio-actions.test.js
Labels: enhancement
