Repository RedHatInsights/catalog-ui, pull requests merged in 2019-02, with the labels that each got.

#84 Use PF4 data list to show orders.
  package-lock.json
  package.json
  src/App.scss
  src/Routes.js
  src/SmartComponents/Order/OrderServiceFormStepConfiguration.js
  src/SmartComponents/Order/Orders.js
  src/SmartComponents/Order/orders-toolbar.js
  src/SmartComponents/Order/orders.scss
  src/test/redux/actions/portfolio-actions.test.js
Labels: enhancement

#85 Update api 0.1.0
  package-lock.json
  package.json
  src/Utilities/Constants.js
  src/redux/Actions/OrderActions.js
  src/redux/Actions/PlatformActions.js
  src/redux/Actions/PortfolioActions.js
  src/test/redux/actions/platform-actions.test.js
  src/test/redux/actions/portfolio-actions.test.js
Labels: enhancement, test

#88 Non archived service offerings
  config/setupTests.js
  package-lock.json
  package.json
  src/App.js
  src/Helpers/Platform/PlatformHelper.js
  src/test/.eslintrc
  src/test/redux/actions/platform-actions.test.js
Labels: enhancement

#90 Added api error key form portfolio validation.
  src/Utilities/store.js
  src/redux/Actions/PortfolioActions.js
Labels: enhancement

#89 Fixed unauthorized error
  src/App.js
  src/PresentationalComponents/Shared/LoaderPlaceholders.js
Labels: bug

#91 Added tests for platform reducer.
  src/test/redux/reducers/platform-reducer.test.js
  src/test/redux/redux-helpers.js
Labels: test

#93 Added tests for order reducer
  src/test/redux/reducers/order-reducer.test.js
Labels: test

#94 Add codecov to travis.
  .gitignore
  .travis.yml
  package.json
Labels: test

#87 Address UX feedback
  package-lock.json
  package.json
  src/App.scss
  src/PresentationalComponents/Platform/PlatformItem.js
  src/PresentationalComponents/Platform/PlatformToolbar.js
  src/PresentationalComponents/Portfolio/AddProductsTitleToolbar.js
  src/PresentationalComponents/Portfolio/PortfolioActionToolbar.js
  src/PresentationalComponents/Portfolio/PortfolioFilterToolbar.js
  src/PresentationalComponents/Portfolio/PortfolioOrderToolbar.js
  src/PresentationalComponents/Portfolio/PortfoliosFilterToolbar.js
  src/PresentationalComponents/Shared/OrderToolbarItem.js
  src/PresentationalComponents/Shared/toolbarschema.scss
  src/PresentationalComponents/Shared/top-toolbar.js
  src/PresentationalComponents/Shared/top-toolbar.scss
  src/SmartComponents/Common/FormRenderer.js
  src/SmartComponents/Common/PlatformSelectToolbar.js
  src/SmartComponents/Order/OrderServiceFormStepConfiguration.js
  src/SmartComponents/Order/orders-toolbar.js
  src/SmartComponents/Order/orders.scss
  src/SmartComponents/Platform/Platform.js
  src/SmartComponents/Platform/Platforms.js
  src/SmartComponents/Portfolio/AddProductsToPortfolio.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/SmartComponents/Portfolio/Portfolios.js
  src/SmartComponents/Portfolio/RemovePortfolioItems.js
  src/SmartComponents/Portfolio/add-portfolio-modal.js
  src/Utilities/jschema.scss
Labels: enhancement

#92 Added tests for portfolio reducer.
  src/redux/reducers/portfolioReducer.js
  src/test/redux/reducers/portfolio-reducer.test.js
Labels: test

#95 Added tests for orders redux action creators.
  src/Helpers/Order/OrderHelper.js
  src/redux/Actions/OrderActions.js
  src/test/redux/actions/order-actions.test.js
Labels: test

#82 Added selection of destination project for order modal
  package-lock.json
  src/Helpers/Portfolio/PortfolioHelper.js
  src/SmartComponents/Common/MainModal.js
  src/SmartComponents/Order/OrderServiceFormStepConfiguration.js
  src/test/redux/actions/portfolio-actions.test.js
Labels: enhancement

#97 Custom select
  .eslintrc.yml
  package.json
  src/PresentationalComponents/Shared/pf4-select-wrapper.js
  src/SmartComponents/Common/FormRenderer.js
Labels: bug

#98 Service offering card update
  src/App.scss
  src/PresentationalComponents/Platform/PlatformItem.js
  src/PresentationalComponents/Platform/platformcard.scss
  src/PresentationalComponents/Shared/CardCommon.js
  src/PresentationalComponents/Shared/service-offering-body.js
  src/SmartComponents/Portfolio/PortfolioItem.js
  src/SmartComponents/Portfolio/portfolioitem.scss
Labels: enhancement

#99 Remove duplicate card checkbox component.
  src/PresentationalComponents/Platform/PlatformItem.js
  src/PresentationalComponents/Shared/CardCheckbox.js
  src/SmartComponents/Common/CardCheckbox.js
  src/SmartComponents/Portfolio/PortfolioItem.js
Labels: technical debt

#100 Added tests for shared presentational components.
  config/setupTests.js
  package-lock.json
  package.json
  src/PresentationalComponents/Platform/PlatformCard.js
  src/PresentationalComponents/Shared/CardCheckbox.js
  src/PresentationalComponents/Shared/CardCommon.js
  src/PresentationalComponents/Shared/FilterToolbarItem.js
  src/PresentationalComponents/Shared/pf4-select-wrapper.js
  src/test/.eslintrc
  src/test/__mocks__/fileMock.js
  src/test/presentional-components/platform/__snapshots__/platform-card.test.js.snap
  src/test/presentional-components/platform/platform-card.test.js
  src/test/presentional-components/shared/404Route.test.js
  src/test/presentional-components/shared/__snapshots__/404Route.test.js.snap
  src/test/presentional-components/shared/__snapshots__/card-checkbox.test.js.snap
  src/test/presentional-components/shared/__snapshots__/card-common.test.js.snap
  src/test/presentional-components/shared/__snapshots__/filter-toolbar-item.test.js.snap
  src/test/presentional-components/shared/__snapshots__/image-with-default.test.js.snap
  src/test/presentional-components/shared/__snapshots__/loader-placeholders.test.js.snap
  src/test/presentional-components/shared/__snapshots__/order-toolbar-item.test.js.snap
  src/test/presentional-components/shared/__snapshots__/pf4-select-wrapper.test.js.snap
  src/test/presentional-components/shared/__snapshots__/service-offering-body.test.js.snap
  src/test/presentional-components/shared/__snapshots__/top-toolbar.test.js.snap
  src/test/presentional-components/shared/card-checkbox.test.js
  src/test/presentional-components/shared/card-common.test.js
  src/test/presentional-components/shared/filter-toolbar-item.test.js
  src/test/presentional-components/shared/image-with-default.test.js
  src/test/presentional-components/shared/loader-placeholders.test.js
  src/test/presentional-components/shared/order-toolbar-item.test.js
  src/test/presentional-components/shared/pf4-select-wrapper.test.js
  src/test/presentional-components/shared/service-offering-body.test.js
  src/test/presentional-components/shared/top-toolbar.test.js
Labels: technical debt, test

#102 Fixed dependencies security vulnerabilities.
  package-lock.json
  package.json
Labels: technical debt

#103 Added real parameters to submit order action.
  src/Helpers/Order/OrderHelper.js
  src/test/redux/actions/order-actions.test.js
Labels: bug

#101 Tests for platform smart components.
  config/setupTests.js
  src/SmartComponents/ContentGallery/ContentList.js
  src/SmartComponents/ContentGallery/SearchBar.js
  src/SmartComponents/ContentGallery/content-list.scss
  src/SmartComponents/Platform/Platform.js
  src/SmartComponents/Platform/Platforms.js
  src/test/helpers/shared/user-login.test.js
  src/test/presentational-components/platform/__snapshots__/platform-dashboard.test.js.snap
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/presentational-components/platform/__snapshots__/platform-toolbar.test.js.snap
  src/test/presentational-components/platform/platform-dashboard.test.js
  src/test/presentational-components/platform/platform-item.test.js
  src/test/presentational-components/platform/platform-toolbar.test.js
  src/test/presentional-components/shared/__snapshots__/top-toolbar.test.js.snap
  src/test/presentional-components/shared/top-toolbar.test.js
  src/test/smart-components/content-gallery/__snapshots__/content-gallery.test.js.snap
  src/test/smart-components/content-gallery/content-gallery.test.js
  src/test/smart-components/platform/__snapshots__/platform.test.js.snap
  src/test/smart-components/platform/__snapshots__/platforms.test.js.snap
  src/test/smart-components/platform/platform.test.js
  src/test/smart-components/platform/platforms.test.js
Labels: technical debt, test

#105 Sort orders from newest to oldest.
  src/SmartComponents/Order/Orders.js
Labels: bug

#106 Update api client to match new routing.
  package-lock.json
  package.json
  src/Helpers/Order/OrderHelper.js
  src/Helpers/Portfolio/PortfolioHelper.js
  src/Helpers/Shared/helpers.js
  src/PresentationalComponents/Portfolio/PorfolioCard.js
  src/SmartComponents/Common/OrderModal.js
  src/SmartComponents/Order/OrderServiceFormStepConfiguration.js
  src/SmartComponents/Platform/Platform.js
  src/SmartComponents/Portfolio/AddProductsToPortfolio.js
  src/SmartComponents/Portfolio/Portfolio.js
  src/test/redux/actions/order-actions.test.js
  src/test/redux/actions/portfolio-actions.test.js
Labels: bug, enhancement
