Repository RedHatInsights/catalog-ui, pull requests merged in 2020-07, with the labels that each got.

#615 Update PF4 dependencies to v4
  package-lock.json
  package.json
  src/forms/form-fields/share-group-edit.js
  src/forms/form-fields/share-group-select.js
  src/global-styles.js
  src/presentational-components/platform/platform-item.js
  src/presentational-components/portfolio/portfolio-card-header.js
  src/presentational-components/shared/loader-placeholders.js
  src/presentational-components/shared/pf4-select-wrapper.js
  src/presentational-components/styled-components/table.js
  src/presentational-components/styled-components/toolbars.js
  src/smart-components/common/edit-approval-workflow.js
  src/smart-components/common/form-renderer.js
  src/smart-components/common/order-modal.js
  src/smart-components/content-gallery/content-gallery.js
  src/smart-components/error-pages/common-api-error.js
  src/smart-components/order/cancel-order-modal.js
  src/smart-components/order/order-detail/approval-request.js
  src/smart-components/order/order-detail/order-detail-title.js
  src/smart-components/order/order-detail/order-detail.js
  src/smart-components/order/order-item.js
  src/smart-components/order/orders-list.js
  src/smart-components/platform/service-offering/service-offering-detail.js
  src/smart-components/portfolio/add-portfolio-modal.js
  src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/smart-components/portfolio/portfolio-item.js
  src/smart-components/portfolio/remove-portfolio-modal.js
  src/smart-components/portfolio/share-portfolio-modal.js
  src/smart-components/survey-editing/survey-editor.js
  src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
  src/test/presentational-components/shared/__snapshots__/filter-toolbar-item.test.js.snap
  src/test/presentational-components/shared/__snapshots__/loader-placeholders.test.js.snap
  src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap
  src/test/smart-components/content-gallery/__snapshots__/content-gallery.test.js.snap
  src/test/smart-components/order/__snapshots__/orders.test.js.snap
  src/test/smart-components/platform/platform-inventories.test.js
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap
Labels: dependencies

#640 Fixed missing breadcrumbs separator
  src/smart-components/common/catalog-breadcrumbs.js
  src/smart-components/common/catalog-link.js
  src/test/smart-components/common/catalog-breadcrumbs.test.js
Labels: bug

#644 Add cancel button to order modal.
  src/smart-components/common/order-modal.js
Labels: bug

#646 Add shared label
  src/presentational-components/portfolio/porfolio-card.js
  src/presentational-components/styled-components/card.js
  src/redux/reducers/portfolio-reducer.js
  src/test/integration/portfolio-integration.test.js
  src/test/integration/portfolio-item-integration.test.js
  src/test/integration/portfolio-share-workflow.test.js
  src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/presentational-components/portfolio/portfolio-card.test.js
  src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap
  src/test/redux/reducers/portfolio-reducer.test.js
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/test/smart-components/portfolio/add-portfolio-modal.test.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/test/smart-components/portfolio/portfolios.test.js
  src/test/smart-components/portfolio/remove-portfolio-modal.test.js
  src/test/smart-components/portfolio/share-portfolio-modal.test.js
Labels: enhancement

#647 Fixed outdated toolbar layout.
  src/presentational-components/styled-components/toolbars.js
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
  src/test/smart-components/order/__snapshots__/orders.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/toolbar/helpers.js
  src/toolbar/schemas/add-products-toolbar.schema.js
  src/toolbar/schemas/portfolio-toolbar.schema.js
  src/toolbar/schemas/portfolios-toolbar.schema.js
  src/toolbar/schemas/products-toolbar.schema.js
  src/toolbar/toolbar-mapper.js
Labels: bug

#657 Fixed copy select reset
  src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
Labels: bug

#661 Update order modal styling
  src/smart-components/common/order-modal.js
Labels: enhancement

#663 Switch order detail to tabs layout
  src/global-styles.js
  src/presentational-components/shared/app-tabs.js
  src/presentational-components/styled-components/orders.js
  src/smart-components/order/order-detail/order-detail-menu.js
  src/smart-components/order/order-detail/order-detail.js
  src/test/smart-components/order/__snapshots__/orders.test.js.snap
  src/toolbar/schemas/orders-toolbar.schema.js
Labels: enhancement

#665 Order detail cards
  src/helpers/order/order-helper.js
  src/messages/orders.messages.js
  src/messages/states.messages.js
  src/smart-components/order/order-detail/approval-request.js
  src/smart-components/order/order-detail/order-detail.js
  src/smart-components/order/order-detail/order-details.js
  src/smart-components/order/order-detail/order-lifecycle.js
Labels: enhancement

#669 Update DDF to fix select menu glitches.
  package-lock.json
  package.json
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
Labels: bug

#677 Add portfolio item count to portfolio card
  src/presentational-components/portfolio/porfolio-card.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
Labels: enhancement

#676 Added back button to products.
  src/messages/portfolio.messages.js
  src/presentational-components/portfolio/back-to-products.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/smart-components/portfolio/portfolio-items.js
  src/smart-components/portfolio/portfolio.js
  src/smart-components/products/products.js
  src/toolbar/schemas/portfolio-toolbar.schema.js
Labels: enhancement

#679 Update portfolio item edit
  src/constants/routes.js
  src/helpers/shared/breadcrumbs-creators.js
  src/messages/portfolio.messages.js
  src/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.js
  src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
  src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js
Labels: enhancement

#683 Give product set approval component higher priority.
  src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
Labels: bug

#678 Share modal refactor
  src/forms/form-fields/share-group-edit.js
  src/forms/form-fields/share-group-select.js
  src/forms/portfolio-share-form.schema.js
  src/global-styles.js
  src/messages/portfolio.messages.js
  src/messages/schemas.messages.js
  src/presentational-components/styled-components/level.js
  src/redux/actions/share-actions.js
  src/smart-components/portfolio/share-portfolio-modal.js
  src/test/forms/portfolio-share.schema.test.js
  src/test/integration/portfolio-share-workflow.test.js
  src/test/smart-components/portfolio/share-portfolio-modal.test.js
Labels: enhancement, unmergeable

#685 Add missing grow property to product toolbar
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
Labels: bug

#686 Update delete portfolio modal
  src/messages/portfolio.messages.js
  src/smart-components/portfolio/remove-portfolio-modal.js
Labels: enhancement

#682 Fix copy select value
  package-lock.json
  package.json
  src/forms/form-fields/copy-name-display.js
  src/messages/labels.messages.js
  src/smart-components/common/form-renderer.js
  src/smart-components/dialog-routes/portfolio-routes.js
  src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
  src/test/integration/portfolio-item-integration.test.js
Labels: bug

#662 Add order process list page
  package-lock.json
  src/App.js
  src/Routes.js
  src/constants/routes.js
  src/helpers/order-process/order-process-helper.js
  src/messages/filtering.messages.js
  src/messages/forms.messages.js
  src/messages/labels.messages.js
  src/messages/order-processes.messages.js
  src/messages/portfolio.messages.js
  src/presentational-components/shared/table-empty-state.js
  src/presentational-components/shared/table-toolbar-view.js
  src/redux/action-types.js
  src/redux/actions/order-process-actions.js
  src/redux/reducers/order-process-reducer.js
  src/smart-components/order-process/order-process-table-helpers.js
  src/smart-components/order-process/order-processes.js
  src/smart-components/portfolio/remove-portfolio-modal.js
  src/smart-components/portfolio/share-portfolio-modal.js
  src/test/smart-components/order-process/__snapshots__/order-processes.test.js.snap
  src/test/smart-components/order-process/order-processes.test.js
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/test/utilities/store.test.js
  src/utilities/constants.js
  src/utilities/store.js
Labels: enhancement

#691 Update add portfolio notification
  src/messages/portfolio.messages.js
  src/redux/actions/portfolio-actions.js
  src/smart-components/portfolio/add-portfolio-modal.js
  src/test/redux/actions/portfolio-actions.test.js
Labels: enhancement

#690 Add advanced filtering to portfolios screen
  package-lock.json
  src/helpers/portfolio/portfolio-helper.js
  src/messages/labels.messages.js
  src/messages/order-processes.messages.js
  src/messages/portfolio.messages.js
  src/messages/states.messages.js
  src/presentational-components/styled-components/toolbars.js
  src/redux/actions/portfolio-actions.js
  src/smart-components/order-process/order-processes.js
  src/smart-components/order/orders-list.js
  src/smart-components/platform/platform-inventories.js
  src/smart-components/platform/service-offering/service-offering-detail.js
  src/smart-components/portfolio/add-portfolio-modal.js
  src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
  src/smart-components/portfolio/portfolios.js
  src/smart-components/portfolio/toolbars/portfolios-primary-toolbar.js
  src/test/integration/portfolio-item-integration.test.js
  src/test/integration/portfolio-share-workflow.test.js
  src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
  src/test/presentational-components/portfolio/portfolios-filter-toolbar.test.js
  src/test/redux/actions/portfolio-actions.test.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/test/smart-components/portfolio/portfolios.test.js
  src/test/smart-components/portfolio/remove-portfolio-modal.test.js
  src/test/utilities/portfolio-toolbar.schema.test.js
  src/toolbar/helpers.js
  src/toolbar/schemas/portfolio-toolbar.schema.js
  src/toolbar/schemas/portfolios-toolbar.schema.js
  src/utilities/empty-data-middleware.js
Labels: enhancement

#700 Copy created messages to states messages
  src/messages/states.messages.js
Labels: bug

#693 Update edit workflow process modal
  package-lock.json
  package.json
  src/forms/edit-workflow_form.schema.js
  src/forms/form-fields/initial-chips.js
  src/global-styles.js
  src/smart-components/common/edit-approval-workflow.js
  src/smart-components/common/form-renderer.js
  src/test/smart-components/common/edit-approval-workflow.test.js
  src/test/smart-components/platform/platform-inventories.test.js
Labels: enhancement

#704 Add missing "grow" property to service offering detail header
  src/smart-components/platform/service-offering/service-offering-detail.js
Labels: bug

#705 Update remove products notification message.
  src/messages/portfolio.messages.js
  src/redux/actions/portfolio-actions.js
  src/smart-components/portfolio/portfolio-items.js
  src/smart-components/portfolio/portfolio.js
  src/test/redux/actions/portfolio-actions.test.js
Labels: enhancement

#701 Custom format messages
  src/forms/form-fields/copy-name-display.js
  src/forms/form-fields/share-group-edit.js
  src/forms/form-fields/share-group-select.js
  src/presentational-components/order/order-notification.js
  src/presentational-components/portfolio/back-to-products.js
  src/presentational-components/portfolio/porfolio-card.js
  src/presentational-components/shared/content-list.js
  src/presentational-components/shared/loader-placeholders.js
  src/presentational-components/shared/pf4-select-wrapper.js
  src/smart-components/common/edit-approval-workflow.js
  src/smart-components/common/form-renderer.js
  src/smart-components/content-gallery/content-gallery.js
  src/smart-components/error-pages/common-api-error.js
  src/smart-components/order/cancel-order-modal.js
  src/smart-components/order/order-detail/approval-request.js
  src/smart-components/order/order-detail/order-detail-information.js
  src/smart-components/order/order-detail/order-detail-menu.js
  src/smart-components/order/order-detail/order-detail-title.js
  src/smart-components/order/order-detail/order-detail.js
  src/smart-components/order/order-detail/order-details.js
  src/smart-components/order/order-detail/order-lifecycle.js
  src/smart-components/order/order-detail/order-toolbar-actions.js
  src/smart-components/order/order-item.js
  src/smart-components/order/orders-list.js
  src/smart-components/platform/platform-inventories.js
  src/smart-components/platform/platform-templates.js
  src/smart-components/platform/platforms.js
  src/smart-components/platform/service-offering/service-offering-detail.js
  src/smart-components/portfolio/add-portfolio-modal.js
  src/smart-components/portfolio/add-products-to-portfolio/add-products-gallery.js
  src/smart-components/portfolio/portfolio-empty-state.js
  src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
  src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
  src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
  src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js
  src/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/smart-components/portfolio/portfolio-items.js
  src/smart-components/portfolio/portfolios.js
  src/smart-components/portfolio/remove-portfolio-modal.js
  src/smart-components/portfolio/share-portfolio-modal.js
  src/smart-components/portfolio/toolbars/portfolios-primary-toolbar.js
  src/smart-components/products/products.js
  src/test/utilities/__snapshots__/use-format-message.test.js.snap
  src/test/utilities/use-format-message.test.js
  src/utilities/use-format-message.js
Labels: enhancement
