Repository RedHatInsights/catalog-ui, pull requests merged in 2020-05, with the labels that each got.

#555 Fixed missing filtering options after adding/editing portfolio.
  src/presentational-components/portfolio/porfolio-card.js
  src/redux/actions/portfolio-actions.js
  src/smart-components/common/catalog-link.js
  src/smart-components/common/edit-approval-workflow.js
  src/smart-components/portfolio/add-portfolio-modal.js
  src/smart-components/portfolio/portfolios.js
  src/smart-components/portfolio/remove-portfolio-modal.js
  src/smart-components/portfolio/share-portfolio-modal.js
  src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
  src/test/presentational-components/shared/__snapshots__/conditional-link.test.js.snap
  src/test/redux/actions/portfolio-actions.test.js
  src/test/smart-components/common/__snapshots__/edit-approval-workflow.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/utilities/use-enhanced-history.js
Labels: bug

#556 build sizes optimizations
  config/webpack.config.js
  package-lock.json
  package.json
  src/App.js
  src/Routes.js
  src/global-styles.js
  src/presentational-components/shared/loader-placeholders.js
  src/test/presentational-components/shared/__snapshots__/loader-placeholders.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
Labels: technical debt

#560 Prevent order approval tab from crashing when data is missing.
  src/smart-components/order/order-detail/approval-request.js
  src/test/smart-components/order/order-detail.test.js
Labels: bug

#561 Fix request sequence after portfolio update.
  src/redux/reducers/portfolio-reducer.js
  src/smart-components/portfolio/add-portfolio-modal.js
Labels: bug

#562 Add copy option to portfolio card dropdown.
  src/presentational-components/portfolio/porfolio-card.js
  src/smart-components/portfolio/portfolios.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/presentational-components/portfolio/portfolio-card.test.js
Labels: enhancement

#563 Hide add source button for non org admins on producst page
  src/smart-components/products/products.js
  src/test/smart-components/products/products.test.js
Labels: bug

#564 Ignore all 400 and 404 responses in order detail.
  src/helpers/order/order-helper.js
  src/smart-components/order/order-detail/approval-request.js
  src/smart-components/order/order-detail/order-detail.js
  src/smart-components/order/order-detail/order-details.js
Labels: bug

#569 Add missing CSS
  src/App.js
Labels: bug

#581 Fixed portfolio reload after copy product action.
  src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
Labels: bug

#586 Fixed missing order resources message
  src/smart-components/order/order-detail/order-detail.js
Labels: bug

#599 Use 403 as a default unauthorized route.
  src/smart-components/error-pages/error-redirects.js
  src/test/routing/catalog-route.test.js
  src/test/smart-components/portfolio/add-portfolio-modal.test.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/test/smart-components/portfolio/remove-portfolio-modal.test.js
  src/test/smart-components/portfolio/share-portfolio-modal.test.js
Labels: bug

#589 Improve the viewState hash routing
  package-lock.json
  package.json
  src/utilities/view-state-middleware.js
Labels: enhancement
