Repository RedHatInsights/catalog-ui, pull requests merged in 2020-04, with the labels that each got.

#490 Remove console warnings from tests.
  package-lock.json
  src/presentational-components/shared/content-gallery-empty-state.js
  src/presentational-components/shared/filter-toolbar-item.js
  src/presentational-components/styled-components/styled-gallery.js
  src/redux/actions/platform-actions.js
  src/smart-components/platform/platforms.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/presentational-components/portfolio/portfolio-card-header.test.js
  src/test/presentational-components/shared/__snapshots__/filter-toolbar-item.test.js.snap
  src/test/redux/actions/order-actions.test.js
  src/test/smart-components/common/__snapshots__/edit-approval-workflow.test.js.snap
  src/test/smart-components/common/edit-approval-workflow.test.js
  src/test/smart-components/portfolio/__snapshots__/add-portfolio-modal.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/test/smart-components/portfolio/add-portfolio-modal.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/portfolio-item-detail-toolbar.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.test.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/test/smart-components/products/products.test.js
  src/utilities/use-is-mounted.js
Labels: technical debt, test

#500 Replace workflow term by approval process in notification.
  src/redux/actions/approval-actions.js
Labels: bug

#499 Filter portfolio item targets based on capability
  src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
Labels: bug

#491 Add additional tests
  config/setupTests.js
  package-lock.json
  package.json
  src/constants/select-styles-override.js
  src/forms/portfolio-form.schema.js
  src/helpers/order/order-helper.js
  src/helpers/portfolio/__mocks__/portfolio-helper.js
  src/helpers/shared/__mocks__/user-login.js
  src/presentational-components/portfolio/porfolio-card.js
  src/presentational-components/portfolio/portfolio-card-header.js
  src/presentational-components/shared/content-gallery-empty-state.js
  src/redux/actions/order-actions.js
  src/redux/actions/portfolio-actions.js
  src/smart-components/portfolio/portfolios.js
  src/smart-components/portfolio/remove-portfolio-modal.js
  src/test/.eslintrc
  src/test/forms/portfolio-form.schema.test.js
  src/test/helpers/approval/approval-helper.test.js
  src/test/helpers/order/order-helper.test.js
  src/test/helpers/share/share-helper.test.js
  src/test/integration/__snapshots__/portfolio-integration.test.js.snap
  src/test/integration/portfolio-integration.test.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/presentational-components/portfolio/portfolios-filter-toolbar.test.js
  src/test/redux/actions/approval-actions.test.js
  src/test/redux/actions/order-actions.test.js
  src/test/redux/actions/platform-actions.test.js
  src/test/redux/actions/portfolio-actions.test.js
  src/test/redux/actions/rbac-actions.test.js
  src/test/smart-components/common/edit-approval-workflow.test.js
  src/test/smart-components/common/order-modal.test.js
  src/test/smart-components/order/orders.test.js
  src/test/smart-components/platform/platform-inventories.test.js
  src/test/smart-components/platform/platform-templates.test.js
  src/test/smart-components/platform/platforms.test.js
  src/test/smart-components/platform/service-offering/service-offering-detail.test.js
  src/test/smart-components/portfolio/add-portfolio-modal.test.js
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/test/smart-components/portfolio/portfolios.test.js
  src/test/smart-components/portfolio/remove-portfolio-modal.test.js
  src/test/smart-components/portfolio/share-portfolio-modal.test.js
  src/test/smart-components/products/products.test.js
  src/toolbar/schemas/portfolio-toolbar.schema.js
Labels: technical debt, test

#501 Portfolio item integration
  src/redux/actions/portfolio-actions.js
  src/smart-components/portfolio/portfolio-empty-state.js
  src/test/integration/portfolio-item-integration.test.js
  src/toolbar/schemas/add-products-toolbar.schema.js
Labels: pending, technical debt, test

#504 Remove vendor name under the product icon.
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
Labels: bug

#505 Fixed styled card body spacing.
  src/presentational-components/styled-components/card.js
  src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
Labels: bug

#502 Update portfolio items after location change.
  src/smart-components/portfolio/portfolio.js
  src/utilities/use-is-mounted.js
Labels: bug

#503 Replace portfolio item kebab with toolbar buttons.
  src/test/smart-components/portfolio/portfolio.test.js
  src/toolbar/schemas/portfolio-toolbar.schema.js
Labels: bug

#506 Fixed empty space under add products bottom pagination.
  src/smart-components/portfolio/add-products-to-portfolio/add-products-gallery.js
  src/smart-components/portfolio/add-products-to-portfolio/index.js
Labels: bug

#509 Change the order item link based on order state.
  src/constants/routes.js
  src/smart-components/order/order-item.js
Labels: enhancement

#510 Use portfolio directly from selectedPortfolio in portfolio item detail.
  src/redux/actions/portfolio-actions.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
Labels: bug

#507 Use API pagination and filtering when adding products.
  src/presentational-components/shared/filter-toolbar-item.js
  src/smart-components/portfolio/add-products-to-portfolio/index.js
  src/test/integration/portfolio-item-integration.test.js
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
  src/toolbar/schemas/add-products-toolbar.schema.js
Labels: bug

#514 Portfolio approval share full APP testing
  src/helpers/approval/approval-helper.js
  src/helpers/portfolio/portfolio-helper.js
  src/helpers/share/share-helper.js
  src/presentational-components/portfolio/porfolio-card.js
  src/redux/actions/portfolio-actions.js
  src/smart-components/portfolio/portfolios.js
  src/test/integration/portfolio-integration.test.js
  src/test/integration/portfolio-item-integration.test.js
  src/test/smart-components/common/edit-approval-workflow.test.js
  src/test/smart-components/platform/platform-inventories.test.js
Labels: test

#511 Encode view state to URL fragment
  src/redux/actions/order-actions.js
  src/redux/actions/portfolio-actions.js
  src/routing/uri-state-manager.js
  src/routing/use-initial-uri-hash.js
  src/smart-components/order/orders-list.js
  src/smart-components/portfolio/portfolio.js
  src/smart-components/portfolio/portfolios.js
  src/smart-components/products/products.js
  src/test/redux/actions/portfolio-actions.test.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/test/smart-components/portfolio/portfolios.test.js
  src/utilities/store.js
  src/utilities/view-state-middleware.js
Labels: enhancement

#515 Fix button variants in edit product form.
  package-lock.json
  src/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.js
Labels: bug

#529 Add share portfolio form validation
  src/forms/form-fields/share-group-select.js
  src/forms/portfolio-share-form.schema.js
  src/smart-components/portfolio/share-portfolio-modal.js
Labels: bug

#530 Small update to the order's approval tab
  src/smart-components/order/order-detail/approval-request.js
Labels: bug

#532 Add unauthorized middleware.
  package-lock.json
  package.json
  src/Routes.js
  src/helpers/shared/user-login.js
  src/router.js
  src/smart-components/error-pages/common-api-error.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/utilities/store.js
  src/utilities/unauthorized-middleware.js
Labels: enhancement

#540 Fixed missing add products to portfolio button.
  src/smart-components/portfolio/portfolio-empty-state.js
  src/smart-components/portfolio/portfolio-items.js
  src/test/smart-components/portfolio/portfolio-empty-state.test.js
Labels: bug

#541 Redirect to the newly created portfolio page
  src/helpers/portfolio/portfolio-helper.js
  src/redux/actions/portfolio-actions.js
  src/smart-components/portfolio/add-portfolio-modal.js
  src/test/integration/portfolio-integration.test.js
  src/test/redux/actions/portfolio-actions.test.js
Labels: enhancement
