Repository RedHatInsights/catalog-ui, pull requests merged in 2020-08, with the labels that each got.

#706 Update share modal message
  src/helpers/portfolio/share-portfolio-message.js
  src/messages/portfolio.messages.js
  src/smart-components/portfolio/share-portfolio-modal.js
  src/test/helpers/porftolio/share-portfolio-message.test.js
Labels: unmergeable

#709 Tag objects with processes
  config/setupTests.js
  src/constants/routes.js
  src/forms/edit-workflow_form.schema.js
  src/forms/set-object-tags.schema.js
  src/helpers/order-process/order-process-helper.js
  src/helpers/portfolio/share-portfolio-message.js
  src/helpers/shared/user-login.js
  src/messages/approval.messages.js
  src/messages/order-processes.messages.js
  src/presentational-components/portfolio/porfolio-card.js
  src/presentational-components/shared/intl-rich-text-components.js
  src/presentational-components/shared/loader-placeholders.js
  src/redux/action-types.js
  src/redux/actions/approval-actions.js
  src/redux/actions/order-process-actions.js
  src/smart-components/common/edit-approval-workflow.js
  src/smart-components/common/tagging-modal.js
  src/smart-components/dialog-routes/portfolio-routes.js
  src/smart-components/order-process/order-processes.js
  src/smart-components/order-process/set-order-process-modal.js
  src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
  src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/test/helpers/porftolio/share-portfolio-message.test.js
  src/test/presentational-components/portfolio/portfolio-card.test.js
  src/test/smart-components/common/edit-approval-workflow.test.js
  src/test/smart-components/common/tagging-modal.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.test.js
  src/test/utilities/portfolio-toolbar.schema.test.js
  src/toolbar/schemas/portfolio-toolbar.schema.js
Labels: enhancement, unmergeable

#717 Add persistent filtering to order processes
  src/redux/action-types.js
  src/redux/actions/order-process-actions.js
  src/smart-components/order-process/order-processes.js
  src/test/smart-components/order-process/order-processes.test.js
Labels: enhancement

#719 Fix runtime error after deleting portfolio from detail.
  src/test/utilities/empty-data-middleware.test.js
  src/utilities/empty-data-middleware.js
Labels: bug

#718 Update orders table
  src/global-styles.js
  src/messages/labels.messages.js
  src/messages/orders.messages.js
  src/presentational-components/styled-components/table.js
  src/redux/actions/order-actions.js
  src/smart-components/order/order-detail/approval-request.js
  src/smart-components/order/order-item.js
  src/smart-components/order/orders-list.js
  src/test/smart-components/order/orders.test.js
Labels: enhancement

#707 Add Remove Order process(es) modal. Order process list selectable
  src/constants/routes.js
  src/helpers/order-process/order-process-helper.js
  src/messages/actions.messages.js
  src/messages/order-processes.messages.js
  src/presentational-components/shared/loader-placeholders.js
  src/presentational-components/shared/table-toolbar-view.js
  src/redux/action-types.js
  src/redux/actions/order-process-actions.js
  src/redux/reducers/order-process-reducer.js
  src/smart-components/order-process/order-process-table-context.js
  src/smart-components/order-process/order-process-table-helpers.js
  src/smart-components/order-process/order-processes.js
  src/smart-components/order-process/remove-order-process-modal.js
  src/test/presentational-components/shared/table-toolbar-view.test.js
  src/test/smart-components/order-process/__snapshots__/remove-order-process-modal.test.js.snap
  src/test/smart-components/order-process/remove-order-process-modal.test.js
  src/utilities/use-order-process.js
Labels: enhancement

#727 Fix major security vulnerabilities
  package-lock.json
Labels: dependencies

#726 update labels colors and icons
  src/smart-components/order/order-detail/order-detail-information.js
  src/smart-components/order/order-item.js
  src/smart-components/order/order-status-mapper.js
Labels: enhancement

#728 Edit edit option to add order process modal.
  src/constants/routes.js
  src/helpers/order-process/order-process-helper.js
  src/messages/order-processes.messages.js
  src/redux/action-types.js
  src/redux/actions/order-process-actions.js
  src/smart-components/order-process/add-order-process-modal.js
  src/smart-components/order-process/order-processes.js
  src/smart-components/order-process/remove-order-process-modal.js
  src/test/smart-components/order-process/__snapshots__/add-order-process-modal.test.js.snap
  src/test/smart-components/order-process/add-order-process-modal.test.js
Labels: enhancement

#735 Order page invalid access
  .eslintrc
  package-lock.json
  package.json
  src/helpers/order/new-order-helper.ts
  src/helpers/order/order-helper.js
  src/helpers/shared/user-login.ts
  src/messages/api-errors.messages.js
  src/router.js
  src/routing/catalog-history.ts
  src/smart-components/error-pages/common-api-error.js
  src/smart-components/order/order-item.js
  src/test/helpers/order/new-order-helper.test.js
  src/types/global.d.ts
  src/utilities/constants.ts
  src/utilities/unauthorized-middleware.js
  src/utilities/view-state-middleware.js
Labels: bug, refactoring

#736 Convert order process async name validator to TS
  src/constants/nullable-attributes.ts
  src/constants/routes.ts
  src/constants/ui-constants.ts
  src/forms/name-async-validator.ts
  src/helpers/order-process/order-process-helper.js
  src/helpers/order-process/order-process-helper.ts
  src/helpers/shared/pagination.js
  src/helpers/shared/pagination.ts
  src/helpers/shared/user-login.ts
  src/messages/forms.messages.ts
  src/types/axios.d.ts
  src/types/common-types.d.ts
  src/utilities/async-form-validator.js
  src/utilities/async-form-validator.ts
  tsconfig.json
Labels: refactoring

#738 Hide portfolio create button for users without permission.
  src/smart-components/portfolio/portfolios.js
  src/smart-components/portfolio/toolbars/portfolios-primary-toolbar.js
  src/test/smart-components/portfolio/portfolios.test.js
Labels: bug

#737 Migrate portfolio form schema to ts
  package-lock.json
  package.json
  src/forms/portfolio-form.schema.ts
  src/helpers/portfolio/__mocks__/portfolio-helper.js
  src/helpers/portfolio/__mocks__/portfolio-helper.ts
  src/helpers/portfolio/portfolio-helper.js
  src/helpers/portfolio/portfolio-helper.ts
  src/helpers/shared/helpers.tsx
  src/helpers/shared/pagination.ts
  src/smart-components/order-process/order-process-table-helpers.js
  src/smart-components/platform/platform-table-helpers.js
  src/smart-components/portfolio/add-portfolio-modal.js
  src/test/forms/__snapshots__/portfolio-form.schema.test.js.snap
  src/test/forms/portfolio-form.schema.test.js
  src/test/redux/actions/portfolio-actions.test.js
  src/types/common-types.d.ts
  src/types/frontend-components.d.ts
Labels: refactoring

#740 Migrate redux files to ts
  package-lock.json
  package.json
  src/redux/action-types.ts
  src/redux/action-types/action-types-helper.ts
  src/redux/action-types/approval-action-types.ts
  src/redux/actions/order-actions.js
  src/redux/reducers/approval-reducer.js
  src/redux/reducers/approval-reducer.ts
  src/redux/reducers/breadcrumbs-reducer.js
  src/redux/reducers/breadcrumbs-reducer.ts
  src/redux/reducers/i18n-reducer.js
  src/redux/reducers/i18n-reducer.ts
  src/redux/reducers/open-api-reducer.js
  src/redux/reducers/open-api-reducer.ts
  src/redux/reducers/order-process-reducer.ts
  src/redux/reducers/order-reducer.ts
  src/redux/reducers/platform-reducer.js
  src/redux/reducers/platform-reducer.ts
  src/redux/reducers/portfolio-reducer.ts
  src/redux/reducers/rbac-reducer.js
  src/redux/reducers/rbac-reducer.ts
  src/redux/reducers/share-reducer.js
  src/redux/reducers/share-reducer.ts
  src/routing/uri-state-manager.ts
  src/test/redux/actions/order-actions.test.js
  src/test/redux/reducers/order-reducer.test.js
  src/types/common-types.d.ts
  src/types/frontend-components.d.ts
  src/types/sources-client.d.ts
  src/utilities/empty-data-middleware.ts
  src/utilities/loading-state-middleware.ts
  src/utilities/store.ts
  src/utilities/unauthorized-middleware.ts
  src/utilities/view-state-middleware.ts
Labels: refactoring
