Repository RedHatInsights/catalog-ui, pull requests merged in 2020-02, with the labels that each got.

#400 Remove unnecessary clients.
  package-lock.json
  package.json
  src/helpers/platform/platform-helper.js
  src/helpers/shared/user-login.js
  src/test/helpers/shared/user-login.test.js
Labels: technical debt

#402 Update survey editor with validation and hide features.
  package-lock.json
  package.json
  src/App.scss
  src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/survey-editing/survey-editor.js
Labels: enhancement

#406 Updated source name for product detail page
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
Labels: bug

#408 Fixed error on Cancel order before approval
  src/redux/actions/order-actions.js
Labels: bug

#409 Use approval_request_ref instead of id.
  src/smart-components/order/order-detail/approval-request.js
Labels: enhancement

#410 Use is valid to disable survey editor submit.
  config/webpack.config.js
  package-lock.json
  package.json
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/survey-editing/survey-editor.js
Labels: enhancement

#411 Remove inline styling where possible
  src/App.js
  src/App.scss
  src/presentational-components/platform/platform-dashboard.js
  src/presentational-components/platform/platform-item.js
  src/presentational-components/portfolio/portfolio-card-header.js
  src/presentational-components/shared/card-checkbox.js
  src/presentational-components/shared/card-icon.js
  src/presentational-components/shared/loader-placeholders.js
  src/presentational-components/shared/service-offering-body.js
  src/smart-components/order/order-item.js
  src/smart-components/platform/service-offering/service-offering-detail.js
  src/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/smart-components/portfolio/portfolio-item.js
  src/test/presentational-components/platform/__snapshots__/platform-dashboard.test.js.snap
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/presentational-components/platform/platform-dashboard.test.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap
  src/test/presentational-components/shared/__snapshots__/card-checkbox.test.js.snap
  src/test/presentational-components/shared/__snapshots__/loader-placeholders.test.js.snap
  src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap
  src/toolbar/schemas/portfolio-toolbar.schema.js
Labels: technical debt

#404 Bundle size optimizations
  .babelrc
  babel.config.js
  config/webpack.config.js
  config/webpack.plugins.js
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/Routes.js
  src/helpers/shared/helpers.js
  src/presentational-components/portfolio/porfolio-card.js
  src/presentational-components/shared/button-with-spinner.js
  src/presentational-components/shared/loader-placeholders.js
  src/smart-components/common/order-modal.js
  src/smart-components/content-gallery/content-gallery.js
  src/smart-components/order/order-detail/approval-request.js
  src/smart-components/order/order-detail/order-detail-information.js
  src/smart-components/order/order-detail/order-detail.js
  src/smart-components/order/order-detail/order-details.js
  src/smart-components/order/order-item.js
  src/smart-components/order/orders-list.js
  src/smart-components/platform/platform-inventories.js
  src/smart-components/platform/service-offering/service-offering-detail.js
  src/smart-components/portfolio/add-portfolio-modal.js
  src/smart-components/portfolio/add-products-to-portfolio/index.js
  src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
  src/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/smart-components/survey-editing/survey-editor.js
  src/test/smart-components/platform/platform-inventories.test.js
Labels: enhancement, technical debt

#415 Fix card header layout on platform item card.
  src/presentational-components/platform/platform-item.js
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
Labels: bug

#417 Remove old, unused topology client
  package-lock.json
  package.json
Labels: technical debt

#416 Refactor add products to portfolio to use redux hooks.
  src/presentational-components/shared/filter-select.js
  src/smart-components/portfolio/add-products-to-portfolio/index.js
  src/smart-components/portfolio/portfolio.js
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
Labels: technical debt

#423 Inject styles instead of extracting them.
  config/webpack.config.js
  config/webpack.plugins.js
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/presentational-components/platform/platform-card.js
  src/presentational-components/platform/platform-card.scss
  src/presentational-components/platform/platform-item.js
  src/presentational-components/portfolio/porfolio-card.js
  src/presentational-components/portfolio/portfolio-card-header.js
  src/presentational-components/portfolio/portfolio-card.scss
Labels: bug

#414 Update survey editor with error indicators.
  package-lock.json
  package.json
Labels: enhancement

#418 Fixed overflow in share portfolio modal.
  src/App.scss
  src/forms/form-fields/shage-group-edit.js
  src/forms/form-fields/share-group-select.js
Labels: bug

#426 Fixed missing dispatch in share portfolio.
  src/smart-components/portfolio/share-portfolio-modal.js
Labels: bug

#425 Migrate to styled components
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/global-styles.js
  src/presentational-components/platform/platform-card.js
  src/presentational-components/platform/platform-item.js
  src/presentational-components/portfolio/porfolio-card.js
  src/presentational-components/portfolio/portfolio-card-header.js
  src/presentational-components/shared/button-with-spinner.js
  src/presentational-components/shared/card-common.js
  src/presentational-components/shared/card-icon.js
  src/presentational-components/shared/filter-toolbar-item.js
  src/presentational-components/shared/loader-placeholders.js
  src/presentational-components/shared/service-offering-body.js
  src/presentational-components/shared/top-toolbar.js
  src/presentational-components/styled-components/ellipsis-text-container.js
  src/presentational-components/styled-components/lazy-load-image.js
  src/presentational-components/styled-components/level.js
  src/presentational-components/styled-components/orders.js
  src/presentational-components/styled-components/styled-gallery.js
  src/presentational-components/styled-components/toolbars.js
  src/smart-components/common/catalog-link.js
  src/smart-components/common/order-modal.js
  src/smart-components/order/order-detail/order-detail.js
  src/smart-components/order/order-item.js
  src/smart-components/platform/service-offering/service-offering-detail.js
  src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
  src/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/portfolio/portfolio-item.js
  src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card-header.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
  src/test/presentational-components/shared/__snapshots__/card-common.test.js.snap
  src/test/presentational-components/shared/__snapshots__/conditional-link.test.js.snap
  src/test/presentational-components/shared/__snapshots__/filter-toolbar-item.test.js.snap
  src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap
  src/test/presentational-components/shared/__snapshots__/top-toolbar.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap
  src/test/smart-components/portfolio/portfolio.test.js
  src/toolbar/helpers.js
  src/toolbar/schemas/platforms-toolbar.schema.js
  src/toolbar/schemas/portfolio-toolbar.schema.js
  src/toolbar/toolbar-mapper.js
Labels: refactoring, technical debt

#431 Fixed clickable disabled links in order detail.
  src/smart-components/order/order-detail/order-detail-menu.js
  src/smart-components/order/order-detail/order-detail.js
Labels: bug

#436 Add portfolio name to product
  package-lock.json
  src/helpers/portfolio/portfolio-helper.js
  src/presentational-components/shared/service-offering-body.js
  src/smart-components/products/products.js
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap
  src/test/redux/actions/portfolio-actions.test.js
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/test/smart-components/products/products.test.js
Labels: enhancement

#438 Survey editor: restrict options value and input type.
  package-lock.json
  package.json
  src/smart-components/survey-editing/survey-editor.js
Labels: enhancement

#441 Remove order button when source is unavailable.
  src/presentational-components/styled-components/level.js
  src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.test.js
Labels: enhancement
