Repository RedHatInsights/catalog-ui, pull requests merged in 2020-06, with the labels that each got.

#608 Update to v2 of fce.
  package-lock.json
  package.json
  src/App.js
  src/helpers/shared/helpers.js
  src/presentational-components/order/order-notification.js
  src/presentational-components/portfolio/porfolio-card.js
  src/redux/actions/approval-actions.js
  src/redux/actions/order-actions.js
  src/redux/actions/portfolio-actions.js
  src/smart-components/content-gallery/content-gallery.js
  src/smart-components/order/order-detail/approval-request.js
  src/smart-components/order/order-detail/order-detail-information.js
  src/smart-components/order/order-detail/order-details.js
  src/smart-components/order/order-item.js
  src/smart-components/order/orders-list.js
  src/smart-components/platform/platform-inventories.js
  src/smart-components/platform/service-offering/service-offering-detail.js
  src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
  src/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/smart-components/survey-editing/survey-editor.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/utilities/store.js
Labels: dependencies

#598 Add workbox service worker
  config/webpack.plugins.js
  package-lock.json
  package.json
  src/entry.js
Labels: enhancement

#516 Update ddf to v2.
  package-lock.json
  package.json
  src/forms/edit-portfolio-item-form.schema.js
  src/forms/edit-workflow_form.schema.js
  src/forms/form-fields/shage-group-edit.js
  src/forms/form-fields/share-group-select.js
  src/forms/portfolio-form.schema.js
  src/presentational-components/shared/filter-select.js
  src/presentational-components/shared/pf4-select-wrapper.js
  src/smart-components/common/form-renderer.js
  src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
  src/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.js
  src/smart-components/survey-editing/survey-editor.js
  src/test/forms/__snapshots__/portfolio-form.schema.test.js.snap
  src/test/forms/portfolio-form.schema.test.js
  src/test/integration/portfolio-integration.test.js
  src/test/presentational-components/shared/__snapshots__/pf4-select-wrapper.test.js.snap
  src/test/presentational-components/shared/pf4-select-wrapper.test.js
  src/test/smart-components/common/edit-approval-workflow.test.js
  src/test/smart-components/portfolio/add-products-to-portfolio/add-products-to-portfolio.test.js
  src/test/smart-components/portfolio/share-portfolio-modal.test.js
Labels: dependencies

#613 Fixed npm security vulnerabilities.
  package-lock.json
  package.json
Labels: dependencies, technical debt

#603 Improve code splitting across the APP
  config/webpack.config.js
  package-lock.json
  package.json
  src/Routes.js
  src/smart-components/dialog-routes/index.js
  src/smart-components/dialog-routes/platform-routes.js
  src/smart-components/dialog-routes/portfolio-routes.js
  src/smart-components/order/order-detail/order-detail.js
  src/smart-components/platform/platform-inventories.js
  src/smart-components/platform/platform-templates.js
  src/smart-components/platform/platform.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/smart-components/portfolio/portfolio-items.js
  src/smart-components/portfolio/portfolio.js
  src/smart-components/portfolio/portfolios.js
  src/test/integration/portfolio-integration.test.js
  src/test/smart-components/platform/platform-inventories.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/portfolio-item-details.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
  src/test/smart-components/portfolio/portfolio.test.js
Labels: enhancement, technical debt

#614 Tests audit
  src/smart-components/order/order-detail/approval-request.js
  src/test/smart-components/common/__snapshots__/edit-approval-workflow.test.js.snap
  src/test/smart-components/common/edit-approval-workflow.test.js
  src/test/smart-components/common/order-modal.test.js
  src/test/smart-components/order/order-detail.test.js
  src/test/smart-components/order/orders.test.js
  src/test/smart-components/platform/platform-inventories.test.js
  src/test/smart-components/platform/platform-templates.test.js
  src/test/smart-components/platform/platforms.test.js
  src/test/smart-components/portfolio/__snapshots__/add-portfolio-modal.test.js.snap
  src/test/smart-components/portfolio/add-portfolio-modal.test.js
Labels: refactoring, test

#625 Fix survey editor not propagating reset changes.
  src/smart-components/survey-editing/survey-editor.js
Labels: bug

#627 Fix security vulnerabilities.
  package-lock.json
  package.json
  src/presentational-components/shared/content-gallery-empty-state.js
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
Labels: dependencies, technical debt

#630 remove unused "breadcrumb-active" class
  src/global-styles.js
Labels: refactoring

#634 removed unneeded example-border class
  src/smart-components/order/orders-list.js
Labels: refactoring
