Repository RedHatInsights/catalog-ui, pull requests merged in 2020-01, with the labels that each got.

#351 Hiding toolbar components when no data in list
  src/helpers/portfolio/portfolio-helper.js
  src/redux/reducers/portfolio-reducer.js
  src/smart-components/common/async-pagination.js
  src/smart-components/order/orders-list.js
  src/smart-components/portfolio/portfolio-items.js
  src/smart-components/portfolio/portfolio.js
  src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
  src/test/presentational-components/portfolio/portfolios-filter-toolbar.test.js
  src/test/redux/actions/portfolio-actions.test.js
  src/test/redux/reducers/portfolio-reducer.test.js
  src/test/smart-components/portfolio/__snapshots__/portfolio.test.js.snap
  src/test/smart-components/portfolio/portfolio.test.js
  src/toolbar/helpers.js
  src/toolbar/schemas/portfolio-toolbar.schema.js
  src/toolbar/schemas/portfolios-toolbar.schema.js
  src/toolbar/schemas/products-toolbar.schema.js
  src/toolbar/toolbar-renderer.js
Labels: enhancement

#356 Removed parent text elements in notifications.
  src/presentational-components/order/order-notification.js
  src/redux/actions/portfolio-actions.js
  src/test/smart-components/portfolio/portfolio.test.js
Labels: refactoring, technical debt

#357 Fixed empty state sources link.
  src/smart-components/platform/platforms.js
Labels: bug

#359 Fixed redirect after portfolio item copy.
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
Labels: bug

#360 fixed card word break
  package-lock.json
  package.json
  src/App.scss
  src/presentational-components/portfolio/portfolio-card.scss
  src/presentational-components/shared/card-common.js
  src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/presentational-components/shared/__snapshots__/card-common.test.js.snap
  src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/remove-portfolio-modal.test.js.snap
  src/test/smart-components/portfolio/remove-portfolio-modal.test.js
Labels: bug

#364 Compact navigation
  src/App.js
  src/App.scss
  src/redux/reducers/platform-reducer.js
  src/smart-components/common/async-pagination.js
  src/smart-components/order/orders-list.js
  src/smart-components/platform/platform-inventories.js
  src/smart-components/platform/platform-templates.js
  src/smart-components/portfolio/add-products-to-portfolio/index.js
  src/smart-components/portfolio/portfolio-items.js
  src/smart-components/portfolio/portfolios.js
  src/smart-components/products/products.js
  src/toolbar/schemas/add-products-toolbar.schema.js
  src/toolbar/schemas/platforms-toolbar.schema.js
  src/toolbar/schemas/portfolio-toolbar.schema.js
  src/toolbar/schemas/portfolios-toolbar.schema.js
  src/toolbar/schemas/products-toolbar.schema.js
Labels: bug, enhancement

#367 Fit and finish part 2
  package.json
  src/App.scss
  src/forms/portfolio-form.schema.js
  src/helpers/shared/helpers.js
  src/presentational-components/portfolio/porfolio-card.js
  src/presentational-components/shared/content-list.js
  src/presentational-components/shared/top-toolbar.js
  src/redux/actions/portfolio-actions.js
  src/smart-components/common/form-renderer.js
  src/smart-components/platform/platform-inventories.js
  src/smart-components/platform/platform-table-helpers.js
  src/smart-components/platform/platform-templates.js
  src/smart-components/portfolio/add-portfolio-modal.js
  src/smart-components/portfolio/remove-portfolio-modal.js
  src/smart-components/products/products.js
  src/test/forms/__snapshots__/portfolio-form.schema.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolios-filter-toolbar.test.js.snap
  src/test/smart-components/portfolio/add-portfolio-modal.test.js
  src/test/smart-components/portfolio/remove-portfolio-modal.test.js
  src/test/smart-components/portfolio/share-portfolio-modal.test.js
  src/toolbar/schemas/platforms-toolbar.schema.js
  src/toolbar/schemas/portfolio-toolbar.schema.js
  src/toolbar/schemas/portfolios-toolbar.schema.js
  src/toolbar/schemas/products-toolbar.schema.js
Labels: enhancement, technical debt

#362 Use portfolio/resource name in modal titles
  src/smart-components/common/edit-approval-workflow.js
  src/smart-components/platform/platform-inventories.js
  src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js
  src/smart-components/portfolio/portfolio-items.js
  src/smart-components/portfolio/portfolios.js
  src/test/smart-components/common/__snapshots__/edit-approval-workflow.test.js.snap
  src/test/smart-components/common/edit-approval-workflow.test.js
Labels: enhancement

#369 Adjusted bottom pagination spacing.
  src/presentational-components/shared/bottom-pagination-container.js
  src/smart-components/platform/platform-inventories.js
  src/smart-components/platform/platform-templates.js
  src/smart-components/platform/platforms.js
  src/smart-components/portfolio/portfolio-items.js
  src/smart-components/portfolio/portfolios.js
Labels: enhancement

#372 Platform service offering
  src/helpers/platform/platform-helper.js
  src/redux/action-types.js
  src/redux/actions/platform-actions.js
  src/redux/reducers/platform-reducer.js
  src/smart-components/platform/platform-templates.js
  src/smart-components/platform/platforms.js
  src/smart-components/platform/service-offering/service-offering-detail.js
  src/test/redux/actions/platform-actions.test.js
  src/test/redux/reducers/platform-reducer.test.js
  src/test/smart-components/platform/service-offering/service-offering-detail.test.js
Labels: enhancement

#377 Added missing filter attribute to remove portfolio item.
  src/redux/actions/portfolio-actions.js
  src/test/redux/actions/portfolio-actions.test.js
Labels: bug

#374 Fallback source icons from platform
  src/App.js
  src/assets/images/amazon-icon.png
  src/assets/images/card-icon-default.png
  src/assets/images/default-portfolio.jpg
  src/assets/images/openshift-icon.svg
  src/assets/images/tower-icon.svg
  src/presentational-components/shared/card-icon.js
  src/redux/action-types.js
  src/redux/reducers/platform-reducer.js
  src/smart-components/common/order-modal.js
  src/smart-components/order/order-item.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/portfolio/portfolio-item.js
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/redux/reducers/platform-reducer.test.js
  src/test/smart-components/common/order-modal.test.js
  src/test/smart-components/order/orders.test.js
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
  src/test/smart-components/portfolio/portfolio-item.test.js
  src/test/smart-components/products/products.test.js
Labels: enhancement

#376 Added description to portfolio detail toolbar.
  src/App.js
  src/App.scss
  src/presentational-components/shared/top-toolbar.js
  src/presentational-components/shared/top-toolbar.scss
  src/smart-components/portfolio/portfolio-items.js
  src/toolbar/schemas/portfolio-toolbar.schema.js
Labels: enhancement

#378 Survey editor patch request
  src/smart-components/survey-editing/survey-editor.js
Labels: technical debt

#379 Fixed missing dispatch bind on unshare portfolio action.
  src/smart-components/portfolio/share-portfolio-modal.js
Labels: bug

#380 Changed copy portfolio select to async select with filter.
  src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
Labels: enhancement

#381 Change toolbar description variant from small to p.
  src/presentational-components/shared/top-toolbar.js
Labels: bug

#382 Enable subset mode for survey editing.
  package-lock.json
  package.json
  src/smart-components/survey-editing/survey-editor.js
Labels: enhancement

#384 Remove extra dollar character from order title.
  src/smart-components/order/order-item.js
Labels: bug

#383 Updated survey editor with PF4 visuals.
  package-lock.json
  package.json
Labels: enhancement

#385 Fixed missing icons for service offerings.
  src/presentational-components/platform/platform-item.js
  src/presentational-components/shared/service-offering-body.js
Labels: bug

#373 Added error handling for image upload.
  src/presentational-components/shared/breadcrubms.js
  src/presentational-components/shared/top-toolbar.js
  src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
Labels: enhancement

#388 Move survey editor from portal to standard page page
  src/App.scss
  src/helpers/shared/helpers.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-breadcrumbs.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/smart-components/survey-editing/survey-editor.js
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
Labels: enhancement, pending

#393 Add initial value to survey editor.
  package-lock.json
  package.json
Labels: enhancement

#392 Fix missing handler for restore portfolio item prev state.
  src/redux/reducers/portfolio-reducer.js
Labels: bug

#396 Added form state to survey editing and restoreable options.
  package-lock.json
  package.json
  src/test/smart-components/common/order-modal.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item.test.js
  src/test/smart-components/portfolio/share-portfolio-modal.test.js
Labels: enhancement

#391 Add notifications to survey editor events.
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/survey-editing/survey-editor.js
Labels: enhancement

#398 Fixed missing initial value in edit workflow modal.
  package-lock.json
  package.json
Labels: bug

#397 Update handling of empty workflow selection
  src/smart-components/common/edit-approval-workflow.js
Labels: bug
