Repository RedHatInsights/catalog-ui, pull requests merged in 2020-03, with the labels that each got.

#442 Enable survey reset
  package-lock.json
  package.json
  src/global-styles.js
  src/presentational-components/shared/button-with-spinner.js
  src/presentational-components/styled-components/level.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/smart-components/survey-editing/survey-editor.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap
Labels: enhancement

#443 Replace frontend components spinner with PF spinner.
  src/presentational-components/shared/button-with-spinner.js
  src/presentational-components/shared/loader-placeholders.js
  src/presentational-components/styled-components/spinner-wrapper.js
  src/smart-components/common/order-modal.js
  src/smart-components/order/order-detail/order-detail.js
  src/smart-components/portfolio/add-portfolio-modal.js
  src/smart-components/portfolio/portfolio-item-detail/icon-upload.js
  src/smart-components/survey-editing/survey-editor.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
Labels: technical debt

#444 Fixed missing section.ins-l-content class.
  src/global-styles.js
Labels: bug

#451 Split survey editor from vendor bundle
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
Labels: technical debt

#450 Added routes permissions.
  src/App.js
  src/Routes.js
  src/routing/catalog-route.js
  src/smart-components/error-pages/common-api-error.js
  src/user-context.js
Labels: enhancement

#453 Exclude css files from tree shaking.
  config/webpack.config.js
  package.json
Labels: bug

#448 Add alert if order resource fails to load.
  src/helpers/order/order-helper.js
  src/presentational-components/styled-components/unavailable-alert-container.js
  src/redux/reducers/order-reducer.js
  src/smart-components/order/order-detail/order-detail.js
  src/test/smart-components/order/orders.test.js
Labels: enhancement

#449 Handle source 404 in portfolio item detail.
  src/helpers/portfolio/portfolio-helper.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
Labels: enhancement

#455 Fix PF card overflow.
  src/presentational-components/platform/platform-card.js
  src/presentational-components/portfolio/porfolio-card.js
  src/presentational-components/shared/service-offering-body.js
  src/presentational-components/styled-components/card.js
  src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/presentational-components/shared/__snapshots__/service-offering-body.test.js.snap
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
Labels: bug

#456 Fixed opened cancel modal after cancel was pressed.
  src/smart-components/order/order-detail/order-toolbar-actions.js
  src/smart-components/order/order-item.js
Labels: bug

#458 Update dependencies with security warnings.
  package-lock.json
  package.json
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
Labels: dependencies

#459 Add autorefresh for approval requests in order detail screen.
  src/helpers/order/order-helper.js
  src/redux/action-types.js
  src/redux/actions/order-actions.js
  src/redux/reducers/order-reducer.js
  src/smart-components/order/order-detail/approval-request.js
Labels: enhancement

#462 Wait for chrome user authentication.
  src/App.js
Labels: bug

#464 Use product instead of portfolio item in portfolio item notification.
  src/redux/actions/portfolio-actions.js
Labels: bug

#465 Update frontend notifications package
  package-lock.json
  package.json
Labels: bug, dependencies

#463 Prefetch select initialValues on first render to avoid missing options.
  src/helpers/approval/approval-helper.js
  src/presentational-components/shared/pf4-select-wrapper.js
  src/test/presentational-components/shared/__snapshots__/pf4-select-wrapper.test.js.snap
  src/test/smart-components/common/edit-approval-workflow.test.js
Labels: bug

#466 Added undo delete portfolio feature.
  src/helpers/portfolio/portfolio-helper.js
  src/redux/actions/portfolio-actions.js
  src/test/redux/actions/portfolio-actions.test.js
  src/test/smart-components/portfolio/remove-portfolio-modal.test.js
Labels: enhancement

#473 Fixed missing permissions for add products button.
  src/smart-components/portfolio/portfolio-empty-state.js
  src/test/smart-components/portfolio/portfolio-empty-state.test.js
Labels: bug

#472 Add check before linking product to portfolio.
  package-lock.json
  src/helpers/portfolio/portfolio-helper.js
Labels: bug

#474 Remove duplicate portfolio fetch
  src/helpers/portfolio/portfolio-helper.js
  src/redux/actions/portfolio-actions.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/item-detail-info-bar.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.test.js
  src/test/smart-components/portfolio/portfolio.test.js
Labels: technical debt

#475 Portfolio user capabilities
  package-lock.json
  package.json
  src/forms/portfolio-share-form.schema.js
  src/presentational-components/portfolio/porfolio-card.js
  src/presentational-components/portfolio/portfolio-card-header.js
  src/redux/reducers/portfolio-reducer.js
  src/routing/catalog-route.js
  src/smart-components/error-pages/error-redirects.js
  src/smart-components/portfolio/add-portfolio-modal.js
  src/smart-components/portfolio/portfolio-items.js
  src/smart-components/portfolio/portfolio.js
  src/smart-components/portfolio/portfolios.js
  src/smart-components/portfolio/remove-portfolio-modal.js
  src/smart-components/portfolio/share-portfolio-modal.js
  src/test/forms/portfolio-share.schema.test.js
  src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
  src/test/presentational-components/portfolio/portfolio-card.test.js
  src/test/redux/reducers/portfolio-reducer.test.js
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/test/smart-components/portfolio/add-portfolio-modal.test.js
  src/test/smart-components/portfolio/portfolio.test.js
  src/test/smart-components/portfolio/portfolios.test.js
  src/test/smart-components/portfolio/remove-portfolio-modal.test.js
  src/test/smart-components/portfolio/share-portfolio-modal.test.js
  src/test/utilities/portfolio-toolbar.schema.test.js
  src/toolbar/schemas/portfolio-toolbar.schema.js
  src/toolbar/toolbar-renderer.js
  src/utilities/constants.js
Labels: enhancement

#478 Add empty state for order approvals.
  src/smart-components/order/order-detail/approval-request.js
Labels: bug

#481 Remove redux logger from production store.
  src/entry.js
  src/utilities/store.js
Labels: technical debt

#476 Portfolio item user capabilities
  src/helpers/shared/helpers.js
  src/redux/reducers/portfolio-reducer.js
  src/routing/catalog-route.js
  src/smart-components/common/catalog-link.js
  src/smart-components/common/edit-approval-workflow.js
  src/smart-components/error-pages/common-api-error.js
  src/smart-components/error-pages/error-redirects.js
  src/smart-components/portfolio/portfolio-item-detail/copy-portfolio-item-modal.js
  src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
  src/smart-components/portfolio/portfolio-item-detail/item-detail-description.js
  src/smart-components/portfolio/portfolio-item-detail/item-detail-info-bar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/smart-components/portfolio/portfolio-item.js
  src/smart-components/portfolio/portfolio-items.js
  src/smart-components/portfolio/portfolio.js
  src/test/presentational-components/platform/__snapshots__/platform-card.test.js.snap
  src/test/presentational-components/shared/__snapshots__/conditional-link.test.js.snap
  src/test/routing/catalog-route.test.js
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/portfolio-item-detail-toolbar.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/portfolio-item-details.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.test.js
  src/test/smart-components/portfolio/portfolio-item-detail/portfolio-item-details.test.js
  src/test/smart-components/portfolio/portfolio-item.test.js
  src/test/smart-components/portfolio/portfolio.test.js
Labels: enhancement

#485 Apply user capabilities on survey editor and icon upload.
  src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail-toolbar.js
  src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
  src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
  src/test/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.test.js
Labels: enhancement

#484 Replace react-content-loader with css implementation.
  package-lock.json
  package.json
  src/App.js
  src/presentational-components/shared/loader-placeholders.js
  src/router.js
  src/test/presentational-components/platform/__snapshots__/platform-item.test.js.snap
  src/test/presentational-components/shared/__snapshots__/loader-placeholders.test.js.snap
  src/test/presentational-components/shared/loader-placeholders.test.js
  src/test/smart-components/portfolio/__snapshots__/portfolio-item.test.js.snap
Labels: bug

#486 Add missing user_capabilities to portfolio placeholders.
  src/redux/reducers/portfolio-reducer.js
Labels: bug

#488 Fixed share portfolio from the card kebab menu
  src/smart-components/portfolio/share-portfolio-modal.js
Labels: bug
